import json

run_id = 'a8c77ab5-ec18-406a-a396-950a4e6eb9a7'

private_memo = """# Morning memo — 2026-05-19

**Source failures:** None observed.

## Worth attention

- **Sx — open-source package manager for AI skills, MCPs, and commands** — https://github.com/sleuth-io/sx
  A new open-source CLI tool (`sx`) for installing, managing, and distributing AI skills, MCP servers, and custom commands. For anyone building MCP-heavy workflows this directly addresses the "how do I package and share MCPs" gap. Early-stage Show HN, but the concept is immediately relevant to agent tooling work. Worth cloning and evaluating.

- **n8n@1.123.44 — patches 11 critical security issues (vm2, protobufjs, langsmith)** — https://github.com/n8n-io/n8n/releases/tag/n8n%401.123.44
  If you self-host n8n on the 1.x LTS track, upgrade now. vm2 (Node sandbox) critical vulnerabilities can allow sandbox escape; protobufjs issues can allow code injection. 11 critical CVEs total. The 2.x stable track (2.20.11) received only minor bug fixes this cycle.

- **crewAI 1.14.5 — deprecates CrewAgentExecutor, defaults to AgentExecutor** — https://github.com/crewAIInc/crewAI/releases/tag/1.14.5
  Stable release deprecates the old `CrewAgentExecutor` in favor of `AgentExecutor`. If you have CrewAI in any pipeline, audit before next deploy. Also adds Daytona sandbox tooling and `restore_from_state_id` for mid-run state recovery — useful for long-running agent tasks.

- **files.md — zero-dependency open-source Obsidian alternative** — https://github.com/zakirullin/files.md
  A minimal markdown-based note system that works directly on your filesystem with no proprietary sync or plugin ecosystem. Relevant to anyone running a second-brain or markdown knowledge store. No content was pre-loaded in the feed item; direct inspection recommended.

## Full digest
- [P] [github] Sx – open-source package manager for AI skills, MCPs, and commands — https://github.com/sleuth-io/sx — New tool for distributing/managing MCPs and AI skills; directly relevant to agent builders.
- [P] [github] n8n@1.123.44 — https://github.com/n8n-io/n8n/releases/tag/n8n%401.123.44 — 11 critical security fixes including vm2 sandbox escape; upgrade immediately if on 1.x.
- [P] [github] crewAI 1.14.5 — https://github.com/crewAIInc/crewAI/releases/tag/1.14.5 — Deprecates CrewAgentExecutor; new Daytona tools, state restore parameter.
- [P] [github] files.md — https://github.com/zakirullin/files.md — Open-source Obsidian alternative using plain filesystem markdown, no lock-in.
- [M] [huggingface] The Open Agent Leaderboard — https://huggingface.co/blog/ibm-research/open-agent-leaderboard — IBM benchmark for comparing open agent frameworks.
- [M] [google] Gemini Deep Research API — https://ai.google.dev/gemini-api/docs/deep-research — Programmatic access to Gemini deep research; potential tool for research-heavy agents.
- [M] [huggingface] PaddleOCR 3.5 with Transformers Backend — https://huggingface.co/blog/PaddlePaddle/paddleocr-transformers — OCR deployable via HuggingFace pipeline; easier doc parsing deployment.
- [R] [github] langchain-tests==1.1.8 — version bounds hotfix, no user-facing changes.
- [R] [github] crewAI 1.14.5a7 — alpha pre-release, covered by stable 1.14.5.
- [R] [reddit] $200k revenue on dictation app — personal milestone story; no technical signal.
- [R] [reddit] 71 users without marketing — inspirational post, no technical content.
- [R] [reddit] Outbound in 2026 — generic marketing opinion.
- [R] [reddit] First £95 revenue — celebratory post, no signal.
- [R] [reddit] $20k MRR, took a job — personal narrative.
- [R] [reddit] what is this subreddit — meta complaint, no signal.
- [R] [reddit] AI character generator API economics — open question, no resolution.
- [R] [reddit] 2339% growth, 2 paying customers — engagement bait.
- [R] [reddit] First paying user psychology — motivational post.
- [R] [reddit] 60 waitlist signups — engagement bait.
- [R] [reddit] URL shortener Bitly alternative — product launch, no unique signal.
- [R] [reddit] AI book discovery engine — product feedback request.
- [R] [reddit] Boring SaaS ideas — generic discussion thread.
- [R] [reddit] 58 active users 1060% increase — engagement bait.
- [R] [reddit] Vibe-coded MVP sweating — common experience, no actionable specifics.
- [R] [reddit] Traffic/customers survey — open question, no conclusions.
- [R] [reddit] SaaS succeeding, mentally strange — personal wellbeing post.
- [R] [reddit] Most annoying budgeting app things — market research question.
- [R] [reddit] Real estate app customer acquisition — marketing question, no answer.
- [R] [reddit] Stoney requirement drift tracker — product launch, no user evidence.
- [R] [reddit] Seedance video SaaS $70K burn — cost question, no resolution.
- [R] [reddit] ZentraLink domain management — product launch in crowded category.
- [R] [vercel] Consolidated Commit Status — good DX for Vercel monorepos; stack-specific.
- [R] [vercel] Firewall-mitigated traffic is free — good pricing change; Vercel-specific.
- [R] [latent-space] The Next War Is Already Here — defense/political op-ed, outside scope.
- [R] [huggingface] Fine-Tuning NVIDIA Cosmos Predict 2.5 — robotics video generation; not relevant.
- [R] [github] n8n stable (2.20.11) — minor bug fix, duplicate entry.
- [R] [github] n8n@2.20.11 — minor VM expression bug fix only.
- [R] [stratechery] Data Center Discontent — infrastructure politics opinion; not actionable.
"""

results = [
  {"raw_item_id":"1a1590a5-658f-4d33-b3b3-95b5d987120d","title":"langchain-tests==1.1.8","summary":"A hotfix release tightening version bounds on langchain-core. No user-facing changes.","raw_claim":"langchain-tests 1.1.8 updates version bounds for langchain-core and bumps lockfiles.","category":"open_source","evidence_level":"reproducible","evidence_sources":["https://github.com/langchain-ai/langchain/releases/tag/langchain-tests%3D%3D1.1.8"],"uncertainty":"","worth_mentioning_reason":"","score_worth_mentioning":1,"score_solo_dev_relevance":1,"score_owner_work_relevance":1,"score_future_work_relevance":1,"score_decision_impact":0,"score_evidence_strength":4,"score_cost_time_leverage":0,"score_risk_reduction":0,"score_business_opportunity":0,"score_hype_risk":0,"score_novelty_penalty":5,"verdict":"reject","verdict_reason":"Pure version bounds hotfix, no user-facing changes."},
  {"raw_item_id":"fc719f51-a5dc-44da-8310-e31ae209c134","title":"crewAI 1.14.5","summary":"The stable CrewAI 1.14.5 release deprecates CrewAgentExecutor and switches default agents to AgentExecutor. It also adds Daytona sandbox tooling, a restore_from_state_id kickoff parameter for mid-run state recovery, and renames ExaSearchTool. If you have any CrewAI pipeline code referencing the old executor, audit before next deploy.","raw_claim":"crewAI 1.14.5 deprecates CrewAgentExecutor and defaults Crew agents to AgentExecutor.","category":"agent_workflow","evidence_level":"reproducible","evidence_sources":["https://github.com/crewAIInc/crewAI/releases/tag/1.14.5"],"uncertainty":"Unclear migration timeline before CrewAgentExecutor is fully removed.","worth_mentioning_reason":"Deprecation of a core class affects any codebase using CrewAI; restore_from_state_id is useful for long-running agent tasks.","score_worth_mentioning":3,"score_solo_dev_relevance":3,"score_owner_work_relevance":2,"score_future_work_relevance":3,"score_decision_impact":3,"score_evidence_strength":4,"score_cost_time_leverage":1,"score_risk_reduction":1,"score_business_opportunity":0,"score_hype_risk":1,"score_novelty_penalty":2,"verdict":"publish_private","verdict_reason":"Notable deprecation affecting CrewAI users plus genuinely useful state restore feature."},
  {"raw_item_id":"008f3b07-9225-42e7-8533-2addeca9d307","title":"crewAI 1.14.5a7","summary":"An alpha pre-release of crewAI deprecating function_calling_llm. Covered by stable 1.14.5.","raw_claim":"crewAI 1.14.5a7 alpha deprecates function_calling_llm field.","category":"agent_workflow","evidence_level":"early_signal","evidence_sources":["https://github.com/crewAIInc/crewAI/releases/tag/1.14.5a7"],"uncertainty":"","worth_mentioning_reason":"","score_worth_mentioning":1,"score_solo_dev_relevance":1,"score_owner_work_relevance":1,"score_future_work_relevance":1,"score_decision_impact":1,"score_evidence_strength":3,"score_cost_time_leverage":0,"score_risk_reduction":0,"score_business_opportunity":0,"score_hype_risk":0,"score_novelty_penalty":5,"verdict":"reject","verdict_reason":"Alpha pre-release, superceded by stable 1.14.5 in same batch."},
  {"raw_item_id":"d5b75ab5-b398-4c69-85fa-efa08c5797d0","title":"crossed 200k revenue on my dictation app, but honestly most of it was from lifetime deal not MRR","summary":"Personal revenue story from a dictation app founder. Mostly lifetime deal revenue, not MRR. No technical signal.","raw_claim":"Blip AI dictation app crossed $200k total revenue, primarily from lifetime deals.","category":"solo_business","evidence_level":"builder_reported","evidence_sources":["https://www.reddit.com/r/SaaS/comments/1tgohgd/"],"uncertainty":"","worth_mentioning_reason":"","score_worth_mentioning":1,"score_solo_dev_relevance":1,"score_owner_work_relevance":0,"score_future_work_relevance":0,"score_decision_impact":0,"score_evidence_strength":2,"score_cost_time_leverage":0,"score_risk_reduction":0,"score_business_opportunity":0,"score_hype_risk":2,"score_novelty_penalty":4,"verdict":"reject","verdict_reason":"Personal milestone story with no actionable signal for other builders."},
  {"raw_item_id":"d2d4b300-78e2-47cd-b545-ac04b666c806","title":"I know 71 users isn't huge but it feels unreal without marketing","summary":"A new builder celebrating 71 users gained organically. Inspirational post with no technical signal.","raw_claim":"A faceless creator SaaS tool gained 71 users with no marketing spend.","category":"solo_business","evidence_level":"builder_reported","evidence_sources":["https://www.reddit.com/r/SaaS/comments/1tgiuy4/"],"uncertainty":"","worth_mentioning_reason":"","score_worth_mentioning":0,"score_solo_dev_relevance":0,"score_owner_work_relevance":0,"score_future_work_relevance":0,"score_decision_impact":0,"score_evidence_strength":1,"score_cost_time_leverage":0,"score_risk_reduction":0,"score_business_opportunity":0,"score_hype_risk":3,"score_novelty_penalty":5,"verdict":"reject","verdict_reason":"Inspirational post with no actionable technical or business signal."},
  {"raw_item_id":"759862ee-87ae-4b47-b7f2-82df0bfa3a32","title":"Outbound in 2026 looks nothing like it did just a few short years ago","summary":"Generic Reddit opinion post on how outbound sales has become noisier since COVID and AI proliferation.","raw_claim":"Outbound sales has become noisier and less predictable since COVID and the rise of AI-generated content.","category":"distribution","evidence_level":"builder_reported","evidence_sources":["https://www.reddit.com/r/SaaS/comments/1tgq2rv/"],"uncertainty":"","worth_mentioning_reason":"","score_worth_mentioning":0,"score_solo_dev_relevance":0,"score_owner_work_relevance":0,"score_future_work_relevance":0,"score_decision_impact":0,"score_evidence_strength":1,"score_cost_time_leverage":0,"score_risk_reduction":0,"score_business_opportunity":0,"score_hype_risk":2,"score_novelty_penalty":5,"verdict":"reject","verdict_reason":"Generic marketing opinion with no actionable content."},
  {"raw_item_id":"a98293a1-9b98-48b6-9083-c7d8957abbc2","title":"It's not much, but my platform just made its first £95","summary":"A founder celebrating their first £95 in revenue. No technical signal.","raw_claim":"A new platform earned its first £95.83 in gross revenue.","category":"solo_business","evidence_level":"builder_reported","evidence_sources":["https://www.reddit.com/r/SaaS/comments/1tgxmwd/"],"uncertainty":"","worth_mentioning_reason":"","score_worth_mentioning":0,"score_solo_dev_relevance":0,"score_owner_work_relevance":0,"score_future_work_relevance":0,"score_decision_impact":0,"score_evidence_strength":1,"score_cost_time_leverage":0,"score_risk_reduction":0,"score_business_opportunity":0,"score_hype_risk":1,"score_novelty_penalty":5,"verdict":"reject","verdict_reason":"Celebratory post with no technical or strategic signal."},
  {"raw_item_id":"dacbcb1f-ab89-4e87-88cc-5108a40a824a","title":"$20k MRR and I still took a job","summary":"A real estate photo editing SaaS founder describes having $20k MRR but choosing employment for stability. Personal narrative, no technical signal.","raw_claim":"A SaaS founder with $20k MRR chose to take employment due to financial instability.","category":"solo_business","evidence_level":"builder_reported","evidence_sources":["https://www.reddit.com/r/SaaS/comments/1tgvyqh/"],"uncertainty":"","worth_mentioning_reason":"","score_worth_mentioning":0,"score_solo_dev_relevance":0,"score_owner_work_relevance":0,"score_future_work_relevance":0,"score_decision_impact":0,"score_evidence_strength":1,"score_cost_time_leverage":0,"score_risk_reduction":0,"score_business_opportunity":0,"score_hype_risk":1,"score_novelty_penalty":4,"verdict":"reject","verdict_reason":"Personal narrative, no actionable technical or business signal."},
  {"raw_item_id":"87cd1a07-a88b-439e-bac3-a1cf010f7b9f","title":"what's even is this subreddit","summary":"A meta-complaint that r/SaaS is mostly builders marketing to other builders. No signal.","raw_claim":"r/SaaS is primarily builders promoting products to other builders.","category":"builder_report","evidence_level":"builder_reported","evidence_sources":["https://www.reddit.com/r/SaaS/comments/1tgux6r/"],"uncertainty":"","worth_mentioning_reason":"","score_worth_mentioning":0,"score_solo_dev_relevance":0,"score_owner_work_relevance":0,"score_future_work_relevance":0,"score_decision_impact":0,"score_evidence_strength":1,"score_cost_time_leverage":0,"score_risk_reduction":0,"score_business_opportunity":0,"score_hype_risk":2,"score_novelty_penalty":5,"verdict":"reject","verdict_reason":"Meta complaint, no signal."},
  {"raw_item_id":"5995a334-e7fb-400f-8d6d-85304718122b","title":"AI character generator SaaS scaling to 100K images/month. API provider with better unit economics?","summary":"A founder asking for image API provider recommendations at 100K images/month scale. No definitive answer in the post.","raw_claim":"An AI character generator SaaS at 100K images/month seeks better image API pricing than current provider.","category":"pricing_cost","evidence_level":"builder_reported","evidence_sources":["https://www.reddit.com/r/SaaS/comments/1th4gni/"],"uncertainty":"No answer or resolution in post.","worth_mentioning_reason":"","score_worth_mentioning":1,"score_solo_dev_relevance":1,"score_owner_work_relevance":0,"score_future_work_relevance":1,"score_decision_impact":0,"score_evidence_strength":1,"score_cost_time_leverage":0,"score_risk_reduction":0,"score_business_opportunity":0,"score_hype_risk":1,"score_novelty_penalty":4,"verdict":"reject","verdict_reason":"Open question with no resolution; not actionable."},
  {"raw_item_id":"317e1d87-6841-427d-8085-bf221f68798c","title":"2,339% growth. 1,800 site visitors. 2 paying customers. 0 marketing spend. 6 months of building.","summary":"A browser extension with 1800 visitors and only 2 paying customers, framed with a 2339% growth headline. Engagement bait.","raw_claim":"A browser extension got 1800 visitors organically with 2 paying customers in 6 months.","category":"distribution","evidence_level":"builder_reported","evidence_sources":["https://www.reddit.com/r/SaaS/comments/1tgrl9y/"],"uncertainty":"","worth_mentioning_reason":"","score_worth_mentioning":0,"score_solo_dev_relevance":0,"score_owner_work_relevance":0,"score_future_work_relevance":0,"score_decision_impact":0,"score_evidence_strength":1,"score_cost_time_leverage":0,"score_risk_reduction":0,"score_business_opportunity":0,"score_hype_risk":4,"score_novelty_penalty":5,"verdict":"reject","verdict_reason":"Engagement bait growth framing with negligible conversion data."},
  {"raw_item_id":"163209a3-ea07-4727-8ef2-afab09cc2642","title":"The first paying user changes your psychology more than your revenue","summary":"Motivational post about the psychological impact of getting a first paying customer. No technical content.","raw_claim":"Getting a first paying customer has a disproportionate psychological impact on founders.","category":"solo_business","evidence_level":"builder_reported","evidence_sources":["https://www.reddit.com/r/SaaS/comments/1tgrc35/"],"uncertainty":"","worth_mentioning_reason":"","score_worth_mentioning":0,"score_solo_dev_relevance":0,"score_owner_work_relevance":0,"score_future_work_relevance":0,"score_decision_impact":0,"score_evidence_strength":1,"score_cost_time_leverage":0,"score_risk_reduction":0,"score_business_opportunity":0,"score_hype_risk":2,"score_novelty_penalty":5,"verdict":"reject","verdict_reason":"Motivational post, no actionable signal."},
  {"raw_item_id":"756e1c1f-b253-492e-86e2-f83090ecca1b","title":"My productivity app just hit 60 people on the waitlist","summary":"Celebratory post about 60 waitlist signups for an unspecified productivity app. Pure engagement bait.","raw_claim":"A productivity app waitlist reached 60 sign-ups in 6 days.","category":"solo_business","evidence_level":"builder_reported","evidence_sources":["https://www.reddit.com/r/SaaS/comments/1tgqmks/"],"uncertainty":"","worth_mentioning_reason":"","score_worth_mentioning":0,"score_solo_dev_relevance":0,"score_owner_work_relevance":0,"score_future_work_relevance":0,"score_decision_impact":0,"score_evidence_strength":1,"score_cost_time_leverage":0,"score_risk_reduction":0,"score_business_opportunity":0,"score_hype_risk":3,"score_novelty_penalty":5,"verdict":"reject","verdict_reason":"Engagement bait, no actionable signal."},
  {"raw_item_id":"81022ab5-90ec-4117-97f1-0427a7d7aff0","title":"I rebuilt my URL shortener as a Bitly alternative with custom domains on the free tier","summary":"A .NET 9 solo dev built a Bitly alternative with custom domains on the free tier. Product feedback post.","raw_claim":"A new URL shortener SaaS offers custom domains on the free tier as a Bitly alternative.","category":"solo_business","evidence_level":"builder_reported","evidence_sources":["https://www.reddit.com/r/SaaS/comments/1th0tg4/"],"uncertainty":"","worth_mentioning_reason":"","score_worth_mentioning":1,"score_solo_dev_relevance":1,"score_owner_work_relevance":0,"score_future_work_relevance":0,"score_decision_impact":0,"score_evidence_strength":2,"score_cost_time_leverage":0,"score_risk_reduction":0,"score_business_opportunity":0,"score_hype_risk":1,"score_novelty_penalty":4,"verdict":"reject","verdict_reason":"Product launch post in a crowded category, no unique technical signal."},
  {"raw_item_id":"8d736ba9-5323-42f5-ab7f-ab63ab929490","title":"We built a personalized AI book discovery engine to fix broken recommendation lists","summary":"Product feedback request for an AI book recommendation service. Not relevant.","raw_claim":"A team built bookstoread.ai, an AI book discovery engine targeting niche reader preferences.","category":"solo_business","evidence_level":"builder_reported","evidence_sources":["https://www.reddit.com/r/SaaS/comments/1tgydcm/"],"uncertainty":"","worth_mentioning_reason":"","score_worth_mentioning":0,"score_solo_dev_relevance":0,"score_owner_work_relevance":0,"score_future_work_relevance":0,"score_decision_impact":0,"score_evidence_strength":1,"score_cost_time_leverage":0,"score_risk_reduction":0,"score_business_opportunity":0,"score_hype_risk":2,"score_novelty_penalty":4,"verdict":"reject","verdict_reason":"Product feedback post, no technical signal."},
  {"raw_item_id":"10bc09a1-0975-40c5-9dec-3d1bd0eab655","title":"What SaaS idea sounds boring but secretly prints money?","summary":"Discussion thread about boring but profitable SaaS verticals (invoicing, compliance, HR). Generic brainstorm.","raw_claim":"Boring vertical SaaS products can be more profitable than trendy AI apps.","category":"solo_business","evidence_level":"builder_reported","evidence_sources":["https://www.reddit.com/r/SaaS/comments/1tgkje5/"],"uncertainty":"","worth_mentioning_reason":"","score_worth_mentioning":0,"score_solo_dev_relevance":0,"score_owner_work_relevance":0,"score_future_work_relevance":0,"score_decision_impact":0,"score_evidence_strength":1,"score_cost_time_leverage":0,"score_risk_reduction":0,"score_business_opportunity":0,"score_hype_risk":1,"score_novelty_penalty":5,"verdict":"reject","verdict_reason":"Generic discussion thread, no actionable content."},
  {"raw_item_id":"dad0f7ca-b883-4bdd-be9f-c4a8fc905a39","title":"Last 28 Days. 58 active users, 1060% increase. No promotions. Just organic searches and cold outreach.","summary":"A student founder citing 1060% growth to 58 users for a YouTube Shorts analytics tool. Engagement bait.","raw_claim":"RetentionMax YouTube Shorts analytics tool grew to 58 active users in 28 days organically.","category":"distribution","evidence_level":"builder_reported","evidence_sources":["https://www.reddit.com/r/SaaS/comments/1th1y1r/"],"uncertainty":"","worth_mentioning_reason":"","score_worth_mentioning":0,"score_solo_dev_relevance":0,"score_owner_work_relevance":0,"score_future_work_relevance":0,"score_decision_impact":0,"score_evidence_strength":1,"score_cost_time_leverage":0,"score_risk_reduction":0,"score_business_opportunity":0,"score_hype_risk":4,"score_novelty_penalty":5,"verdict":"reject","verdict_reason":"Engagement bait, tiny absolute numbers."},
  {"raw_item_id":"3a19ff8c-cae0-46de-807f-8467959ce6e9","title":"Vibe-coded my MVP, got paying customers, now I'm sweating","summary":"A founder used AI tools to quickly build an MVP with paying customers but is now concerned about security holes and auth issues in the AI-generated code. Common experience with no specific actionable guidance.","raw_claim":"Vibe-coded MVPs with paying customers often contain invisible security and auth vulnerabilities.","category":"builder_report","evidence_level":"builder_reported","evidence_sources":["https://www.reddit.com/r/SaaS/comments/1tgo8vq/"],"uncertainty":"","worth_mentioning_reason":"","score_worth_mentioning":1,"score_solo_dev_relevance":2,"score_owner_work_relevance":0,"score_future_work_relevance":1,"score_decision_impact":1,"score_evidence_strength":1,"score_cost_time_leverage":0,"score_risk_reduction":1,"score_business_opportunity":0,"score_hype_risk":2,"score_novelty_penalty":4,"verdict":"reject","verdict_reason":"Common experience post without specific technical guidance or reproducible findings."},
  {"raw_item_id":"19ef70bd-0df6-4af9-bcc7-3c7e272d50d4","title":"Where does the majority of your traffic/customers come from?","summary":"Survey question about traffic sources (SEO, social, paid ads, communities). No data or conclusions.","raw_claim":"Founders vary widely in primary traffic acquisition channels.","category":"distribution","evidence_level":"builder_reported","evidence_sources":["https://www.reddit.com/r/SaaS/comments/1tglxe9/"],"uncertainty":"","worth_mentioning_reason":"","score_worth_mentioning":0,"score_solo_dev_relevance":0,"score_owner_work_relevance":0,"score_future_work_relevance":0,"score_decision_impact":0,"score_evidence_strength":1,"score_cost_time_leverage":0,"score_risk_reduction":0,"score_business_opportunity":0,"score_hype_risk":1,"score_novelty_penalty":5,"verdict":"reject","verdict_reason":"Open survey question with no conclusions."},
  {"raw_item_id":"2f749c2e-e488-438e-8394-e5135b122420","title":"My SaaS is succeeding, but mentally this journey feels strange","summary":"A founder describes emotional ambivalence during a growing SaaS journey. Personal wellbeing post, no technical content.","raw_claim":"Building a successful SaaS can feel psychologically strange or disconnected.","category":"solo_business","evidence_level":"builder_reported","evidence_sources":["https://www.reddit.com/r/SaaS/comments/1tgyro2/"],"uncertainty":"","worth_mentioning_reason":"","score_worth_mentioning":0,"score_solo_dev_relevance":0,"score_owner_work_relevance":0,"score_future_work_relevance":0,"score_decision_impact":0,"score_evidence_strength":1,"score_cost_time_leverage":0,"score_risk_reduction":0,"score_business_opportunity":0,"score_hype_risk":1,"score_novelty_penalty":4,"verdict":"reject","verdict_reason":"Personal wellbeing post, no actionable signal."},
  {"raw_item_id":"404b8911-9d62-4901-813d-b7c97abe40e8","title":"What's the most annoying thing about Rocket Money or budgeting apps?","summary":"Market research question about pain points in budgeting apps. No answers or conclusions in post.","raw_claim":"Users find current budgeting apps frustrating for various unspecified reasons.","category":"solo_business","evidence_level":"builder_reported","evidence_sources":["https://www.reddit.com/r/SaaS/comments/1th4vnx/"],"uncertainty":"","worth_mentioning_reason":"","score_worth_mentioning":0,"score_solo_dev_relevance":0,"score_owner_work_relevance":0,"score_future_work_relevance":0,"score_decision_impact":0,"score_evidence_strength":1,"score_cost_time_leverage":0,"score_risk_reduction":0,"score_business_opportunity":0,"score_hype_risk":1,"score_novelty_penalty":4,"verdict":"reject","verdict_reason":"Open question with no answers or actionable findings."},
  {"raw_item_id":"d11c7fc8-68e4-459a-9359-c7214e07e2ce","title":"How to get customers for Hômeggô - a real estate app?","summary":"A real estate SaaS founder asking for customer acquisition advice. No actionable content in post.","raw_claim":"A new real estate SaaS is struggling to acquire its first users.","category":"distribution","evidence_level":"builder_reported","evidence_sources":["https://www.reddit.com/r/SaaS/comments/1th42ta/"],"uncertainty":"","worth_mentioning_reason":"","score_worth_mentioning":0,"score_solo_dev_relevance":0,"score_owner_work_relevance":0,"score_future_work_relevance":0,"score_decision_impact":0,"score_evidence_strength":1,"score_cost_time_leverage":0,"score_risk_reduction":0,"score_business_opportunity":0,"score_hype_risk":1,"score_novelty_penalty":5,"verdict":"reject","verdict_reason":"Marketing question with no answers; not relevant."},
  {"raw_item_id":"6560a8f0-a283-42fe-b904-37803be9605b","title":"I built a tool that tracks whether your code still matches the original requirement","summary":"Solo dev built Stoney, a tool to detect requirement drift in codebases. Interesting concept but launch post with no traction data.","raw_claim":"Stoney is a new tool that checks if code still aligns with original requirements.","category":"open_source","evidence_level":"builder_reported","evidence_sources":["https://www.reddit.com/r/SaaS/comments/1th017q/"],"uncertainty":"No details on how requirement drift detection works; no user evidence.","worth_mentioning_reason":"","score_worth_mentioning":1,"score_solo_dev_relevance":2,"score_owner_work_relevance":1,"score_future_work_relevance":1,"score_decision_impact":0,"score_evidence_strength":1,"score_cost_time_leverage":0,"score_risk_reduction":0,"score_business_opportunity":0,"score_hype_risk":2,"score_novelty_penalty":3,"verdict":"reject","verdict_reason":"Interesting concept but launch post with no technical details or user evidence."},
  {"raw_item_id":"97b74877-177d-4b6d-a417-114ea554436c","title":"SaaS scaling to 100K Seedance clips/month, $70K+ burn. Better API provider economics?","summary":"A video generation SaaS burning $70K/month on Fal/Seedance API seeking cheaper alternatives. Open question with no answer.","raw_claim":"Running Seedance 2.0 at 100K clips/month via Fal costs ~$70K/month with no obvious cheaper alternative posted.","category":"pricing_cost","evidence_level":"builder_reported","evidence_sources":["https://www.reddit.com/r/SaaS/comments/1th3lgc/"],"uncertainty":"No answer or resolution in post.","worth_mentioning_reason":"","score_worth_mentioning":1,"score_solo_dev_relevance":1,"score_owner_work_relevance":0,"score_future_work_relevance":1,"score_decision_impact":0,"score_evidence_strength":2,"score_cost_time_leverage":0,"score_risk_reduction":0,"score_business_opportunity":0,"score_hype_risk":1,"score_novelty_penalty":3,"verdict":"reject","verdict_reason":"Open question with no resolution; not actionable."},
  {"raw_item_id":"3233f0db-3c49-4fa3-b644-82a902bab98d","title":"ZentraLink","summary":"Launch post for ZentraLink, a domain/DNS/SSL certificate management platform. No user traction or technical differentiation data.","raw_claim":"ZentraLink is launching as a centralized domain, DNS, and SSL certificate management platform.","category":"infrastructure","evidence_level":"builder_reported","evidence_sources":["https://www.reddit.com/r/SaaS/comments/1th3gb1/"],"uncertainty":"","worth_mentioning_reason":"","score_worth_mentioning":0,"score_solo_dev_relevance":1,"score_owner_work_relevance":0,"score_future_work_relevance":0,"score_decision_impact":0,"score_evidence_strength":1,"score_cost_time_leverage":0,"score_risk_reduction":0,"score_business_opportunity":0,"score_hype_risk":1,"score_novelty_penalty":4,"verdict":"reject","verdict_reason":"Generic product launch post in a crowded category."},
  {"raw_item_id":"1c17f51d-d405-4b73-b872-6a74d1d6b757","title":"Show HN: Files.md – Open-source alternative to Obsidian","summary":"files.md is a zero-dependency open-source alternative to Obsidian that works directly on the local filesystem. No proprietary sync, no plugin store. Relevant to anyone maintaining a second-brain, markdown knowledge graph, or local note system who wants full filesystem ownership without lock-in. Show HN item — content not loaded in feed, direct inspection recommended.","raw_claim":"files.md is an open-source, zero-dependency alternative to Obsidian using plain filesystem markdown.","category":"open_source","evidence_level":"builder_reported","evidence_sources":["https://github.com/zakirullin/files.md"],"uncertainty":"No content loaded in feed item; feature depth unknown without direct inspection.","worth_mentioning_reason":"Directly relevant to second-brain and markdown knowledge management; offers filesystem-native alternative to Obsidian without vendor lock-in.","score_worth_mentioning":3,"score_solo_dev_relevance":3,"score_owner_work_relevance":3,"score_future_work_relevance":3,"score_decision_impact":2,"score_evidence_strength":2,"score_cost_time_leverage":2,"score_risk_reduction":1,"score_business_opportunity":0,"score_hype_risk":1,"score_novelty_penalty":2,"verdict":"publish_private","verdict_reason":"Relevant to second-brain/markdown tooling work; genuine open-source alternative to Obsidian worth evaluating."},
  {"raw_item_id":"9e079efb-7ede-4bbc-bb13-db7835d0970c","title":"Show HN: We missed Winamp, so we built an audio player for macOS","summary":"A macOS audio player inspired by Winamp. Not relevant to development or agent workflows.","raw_claim":"A new macOS audio player was built as a spiritual successor to Winamp.","category":"open_source","evidence_level":"builder_reported","evidence_sources":["https://www.advanced-research.net/180db"],"uncertainty":"","worth_mentioning_reason":"","score_worth_mentioning":0,"score_solo_dev_relevance":0,"score_owner_work_relevance":0,"score_future_work_relevance":0,"score_decision_impact":0,"score_evidence_strength":1,"score_cost_time_leverage":0,"score_risk_reduction":0,"score_business_opportunity":0,"score_hype_risk":1,"score_novelty_penalty":3,"verdict":"reject","verdict_reason":"Entertainment/nostalgia project, not relevant."},
  {"raw_item_id":"72fff4b1-bdcb-4528-bbbe-b602eeefdfd5","title":"Show HN: Auto-identity-remove – Automated data broker opt-out runner for macOS","summary":"An open-source macOS tool that automates data broker opt-out requests. Privacy-useful but not directly relevant to development workflows.","raw_claim":"auto-identity-remove automates data broker opt-out requests on macOS.","category":"automation","evidence_level":"builder_reported","evidence_sources":["https://github.com/stephenlthorn/auto-identity-remove"],"uncertainty":"Scope of data brokers covered unknown without reading the repo.","worth_mentioning_reason":"","score_worth_mentioning":1,"score_solo_dev_relevance":1,"score_owner_work_relevance":0,"score_future_work_relevance":0,"score_decision_impact":0,"score_evidence_strength":2,"score_cost_time_leverage":1,"score_risk_reduction":2,"score_business_opportunity":0,"score_hype_risk":0,"score_novelty_penalty":3,"verdict":"reject","verdict_reason":"Useful privacy tool but outside development workflow scope."},
  {"raw_item_id":"b66a447c-92b5-4286-bdd5-73e14a8683e9","title":"Show HN: Sx – an open-source package manager for AI skills, MCPs, and commands","summary":"Sx (sleuth-io/sx) is a new open-source package manager specifically for AI skills, MCP servers, and custom CLI commands. This addresses the emerging problem of distributing and version-managing MCPs across projects — analogous to npm for traditional packages. Show HN early-stage, but directly relevant to MCP builder workflows. Worth cloning and evaluating.","raw_claim":"Sx is an open-source package manager for installing and managing AI skills, MCP servers, and commands.","category":"agent_workflow","evidence_level":"builder_reported","evidence_sources":["https://github.com/sleuth-io/sx"],"uncertainty":"Early-stage; registry size, stability, and adoption unknown without direct testing.","worth_mentioning_reason":"Directly relevant to MCP building and distribution workflows; solves the real problem of MCP package management with no standard solution yet.","score_worth_mentioning":4,"score_solo_dev_relevance":4,"score_owner_work_relevance":4,"score_future_work_relevance":5,"score_decision_impact":3,"score_evidence_strength":2,"score_cost_time_leverage":3,"score_risk_reduction":1,"score_business_opportunity":2,"score_hype_risk":1,"score_novelty_penalty":1,"verdict":"publish_public","verdict_reason":"Directly addresses MCP distribution problem; highly relevant to agent/MCP builder work."},
  {"raw_item_id":"345d82a1-4262-465d-b7ae-a657a5e4260d","title":"Consolidated Commit Status now available on GitHub","summary":"Vercel monorepos can now show a single consolidated commit status on PRs instead of one per project. Useful for Vercel monorepo users, irrelevant otherwise.","raw_claim":"Vercel now supports a single consolidated GitHub commit status for monorepos with multiple projects.","category":"api_platform_change","evidence_level":"vendor_claim","evidence_sources":["https://vercel.com/changelog/consolidated-commit-status-now-available-for-github"],"uncertainty":"","worth_mentioning_reason":"","score_worth_mentioning":1,"score_solo_dev_relevance":2,"score_owner_work_relevance":0,"score_future_work_relevance":1,"score_decision_impact":1,"score_evidence_strength":4,"score_cost_time_leverage":1,"score_risk_reduction":0,"score_business_opportunity":0,"score_hype_risk":0,"score_novelty_penalty":3,"verdict":"reject","verdict_reason":"Useful Vercel DX improvement but stack-specific; not relevant without Vercel."},
  {"raw_item_id":"76304197-7d22-4081-988d-a0a50d331337","title":"Firewall-mitigated traffic is free on Vercel","summary":"Vercel WAF now waives CDN and data transfer charges for blocked/rate-limited traffic. Good pricing news for Vercel users under bot attack, irrelevant otherwise.","raw_claim":"Vercel no longer bills for traffic that its WAF denies, challenges, or rate-limits.","category":"pricing_cost","evidence_level":"vendor_claim","evidence_sources":["https://vercel.com/changelog/web-application-firewall-mitigated-traffic-is-free-on-vercel"],"uncertainty":"","worth_mentioning_reason":"","score_worth_mentioning":1,"score_solo_dev_relevance":2,"score_owner_work_relevance":0,"score_future_work_relevance":1,"score_decision_impact":1,"score_evidence_strength":4,"score_cost_time_leverage":2,"score_risk_reduction":1,"score_business_opportunity":0,"score_hype_risk":0,"score_novelty_penalty":3,"verdict":"reject","verdict_reason":"Good Vercel pricing change but stack-specific; not relevant without Vercel."},
  {"raw_item_id":"55f0918d-bb40-4919-931c-35cbc516d3a7","title":"The Next War Is Already Here. The West Isn't Ready.","summary":"Opinion piece by Ukrainian drone founder Yaroslav Azhnyuk and Noah Smith on AI-guided weapons and Western defense preparedness. Outside scope.","raw_claim":"The West is unprepared for AI-guided drone warfare that Ukraine has pioneered.","category":"builder_report","evidence_level":"builder_reported","evidence_sources":["https://www.latent.space/p/the-fourth-law"],"uncertainty":"","worth_mentioning_reason":"","score_worth_mentioning":0,"score_solo_dev_relevance":0,"score_owner_work_relevance":0,"score_future_work_relevance":0,"score_decision_impact":0,"score_evidence_strength":2,"score_cost_time_leverage":0,"score_risk_reduction":0,"score_business_opportunity":0,"score_hype_risk":3,"score_novelty_penalty":3,"verdict":"reject","verdict_reason":"Defense/political op-ed, outside scope."},
  {"raw_item_id":"6c5b963e-4693-43e7-a4ec-2a2af110ca96","title":"Gemini Deep Research","summary":"Google has made Deep Research available via the Gemini API, enabling programmatic use of its multi-step research agent. Could be a useful component for building research-heavy agent workflows or data enrichment pipelines. No content was loaded for this item; evaluation based on URL and title only.","raw_claim":"Gemini Deep Research is now accessible via the Gemini API for programmatic multi-step research tasks.","category":"api_platform_change","evidence_level":"vendor_claim","evidence_sources":["https://ai.google.dev/gemini-api/docs/deep-research"],"uncertainty":"No content loaded; pricing, rate limits, and actual API capability unknown without reading the docs.","worth_mentioning_reason":"Programmatic deep research access could be a useful component for agent pipelines requiring automated research.","score_worth_mentioning":3,"score_solo_dev_relevance":3,"score_owner_work_relevance":2,"score_future_work_relevance":3,"score_decision_impact":2,"score_evidence_strength":3,"score_cost_time_leverage":3,"score_risk_reduction":0,"score_business_opportunity":2,"score_hype_risk":2,"score_novelty_penalty":2,"verdict":"monitor","verdict_reason":"Potentially useful API capability for agent research workflows; needs direct doc evaluation."},
  {"raw_item_id":"bbf64e76-92ff-4479-a17b-f1fede0db089","title":"Fine-Tuning NVIDIA Cosmos Predict 2.5 with LoRA/DoRA for Robot Video Generation","summary":"NVIDIA guide for fine-tuning Cosmos Predict 2.5 (a robotics video generation model) using LoRA/DoRA. Not relevant to current work scope.","raw_claim":"NVIDIA Cosmos Predict 2.5 can be fine-tuned with LoRA/DoRA for custom robot video generation tasks.","category":"model_change","evidence_level":"vendor_claim","evidence_sources":["https://huggingface.co/blog/nvidia/cosmos-fine-tuning-for-robot-video-generation"],"uncertainty":"","worth_mentioning_reason":"","score_worth_mentioning":0,"score_solo_dev_relevance":0,"score_owner_work_relevance":0,"score_future_work_relevance":0,"score_decision_impact":0,"score_evidence_strength":3,"score_cost_time_leverage":0,"score_risk_reduction":0,"score_business_opportunity":0,"score_hype_risk":2,"score_novelty_penalty":3,"verdict":"reject","verdict_reason":"Robotics video generation niche; not relevant."},
  {"raw_item_id":"491ca9b6-0df1-475a-b377-f5bd955ab84f","title":"PaddleOCR 3.5: Running OCR and Document Parsing Tasks with a Transformers Backend","summary":"PaddleOCR 3.5 can now run via a standard HuggingFace Transformers backend, making deployment simpler for document parsing pipelines without requiring PaddlePaddle-specific infrastructure. Useful if document parsing or OCR is needed in a workflow.","raw_claim":"PaddleOCR 3.5 now supports a HuggingFace Transformers backend for OCR and document parsing.","category":"open_source","evidence_level":"vendor_claim","evidence_sources":["https://huggingface.co/blog/PaddlePaddle/paddleocr-transformers"],"uncertainty":"Content not loaded; performance benchmarks and ease of Transformers integration unknown.","worth_mentioning_reason":"Simpler deployment path for OCR if document parsing becomes a workflow need.","score_worth_mentioning":2,"score_solo_dev_relevance":2,"score_owner_work_relevance":1,"score_future_work_relevance":2,"score_decision_impact":1,"score_evidence_strength":3,"score_cost_time_leverage":2,"score_risk_reduction":0,"score_business_opportunity":1,"score_hype_risk":1,"score_novelty_penalty":2,"verdict":"monitor","verdict_reason":"Useful capability improvement for document parsing; monitor for when OCR is needed."},
  {"raw_item_id":"f64f3ad4-9d60-407c-b1ce-04ebde41d4f3","title":"The Open Agent Leaderboard","summary":"IBM Research has released an open leaderboard for comparing agent frameworks and models on standardized tasks. Useful as a reference when choosing or evaluating agent frameworks. Content not loaded in feed.","raw_claim":"IBM Research published an Open Agent Leaderboard for benchmarking agent frameworks on standardized tasks.","category":"agent_workflow","evidence_level":"vendor_claim","evidence_sources":["https://huggingface.co/blog/ibm-research/open-agent-leaderboard"],"uncertainty":"Content not loaded; which frameworks and benchmark methodology are unknown.","worth_mentioning_reason":"Reference benchmark for agent framework comparison; useful when evaluating framework choices.","score_worth_mentioning":2,"score_solo_dev_relevance":2,"score_owner_work_relevance":2,"score_future_work_relevance":3,"score_decision_impact":2,"score_evidence_strength":2,"score_cost_time_leverage":0,"score_risk_reduction":0,"score_business_opportunity":0,"score_hype_risk":2,"score_novelty_penalty":2,"verdict":"monitor","verdict_reason":"Useful benchmark reference for agent framework selection; worth bookmarking."},
  {"raw_item_id":"89569cb8-e15c-4526-97a3-d843bd901b20","title":"stable","summary":"n8n stable channel release 2.20.11 with only a minor bug fix resolving empty expressions to empty string in the VM evaluator. Duplicate of the n8n@2.20.11 entry. No security content.","raw_claim":"n8n 2.20.11 stable fixes empty expression handling in the VM evaluator.","category":"open_source","evidence_level":"reproducible","evidence_sources":["https://github.com/n8n-io/n8n/releases/tag/stable"],"uncertainty":"","worth_mentioning_reason":"","score_worth_mentioning":1,"score_solo_dev_relevance":1,"score_owner_work_relevance":1,"score_future_work_relevance":1,"score_decision_impact":0,"score_evidence_strength":4,"score_cost_time_leverage":0,"score_risk_reduction":0,"score_business_opportunity":0,"score_hype_risk":0,"score_novelty_penalty":5,"verdict":"reject","verdict_reason":"Minor bug fix release; duplicate of n8n@2.20.11 entry."},
  {"raw_item_id":"b41334f0-79bb-4f45-ba58-37a8e1aa4651","title":"n8n@2.20.11","summary":"n8n 2.20.11 fixes empty expressions resolving to empty string in the VM evaluator. Minor bug fix only, no security content.","raw_claim":"n8n 2.20.11 resolves empty expressions to empty string in the VM evaluator.","category":"open_source","evidence_level":"reproducible","evidence_sources":["https://github.com/n8n-io/n8n/releases/tag/n8n%402.20.11"],"uncertainty":"","worth_mentioning_reason":"","score_worth_mentioning":1,"score_solo_dev_relevance":1,"score_owner_work_relevance":1,"score_future_work_relevance":1,"score_decision_impact":0,"score_evidence_strength":4,"score_cost_time_leverage":0,"score_risk_reduction":0,"score_business_opportunity":0,"score_hype_risk":0,"score_novelty_penalty":5,"verdict":"reject","verdict_reason":"Minor bug fix only; the important n8n security release is 1.123.44."},
  {"raw_item_id":"72d393a3-f057-481a-8abe-ac034d6384c3","title":"n8n@1.123.44","summary":"n8n 1.123.44 (LTS track) patches 11 critical vulnerabilities including vm2 (Node.js sandbox escape risk), protobufjs (code injection risk), langsmith, and one more. If you self-host n8n on the 1.x track, this is a mandatory security upgrade — vm2 critical issues historically allow full sandbox escape in Node.js environments.","raw_claim":"n8n 1.123.44 patches 11 critical security vulnerabilities in vm2, protobufjs, langsmith, and one additional package.","category":"security_risk","evidence_level":"reproducible","evidence_sources":["https://github.com/n8n-io/n8n/releases/tag/n8n%401.123.44"],"uncertainty":"Specific CVE numbers not listed in release notes excerpt; severity based on known vm2 vulnerability history.","worth_mentioning_reason":"Critical security fixes in a widely-used automation platform; vm2 sandbox escapes are high-severity and the LTS track is commonly self-hosted.","score_worth_mentioning":4,"score_solo_dev_relevance":4,"score_owner_work_relevance":2,"score_future_work_relevance":3,"score_decision_impact":5,"score_evidence_strength":4,"score_cost_time_leverage":0,"score_risk_reduction":5,"score_business_opportunity":0,"score_hype_risk":0,"score_novelty_penalty":0,"verdict":"publish_public","verdict_reason":"11 critical security fixes including vm2 sandbox escape risk; mandatory upgrade for n8n 1.x self-hosters."},
  {"raw_item_id":"bd46cf77-b5d5-4c2d-84d0-994ca4dda8c9","title":"Data Center Discontent, Understanding the Opposition, Fixing the Problem","summary":"Stratechery analysis arguing that community opposition to data centers is rational and the only workable solution is financial compensation. Infrastructure politics op-ed, not actionable.","raw_claim":"Community opposition to data centers is understandable and only solvable by paying affected communities.","category":"infrastructure","evidence_level":"builder_reported","evidence_sources":["https://stratechery.com/2026/data-center-discontent-understanding-the-opposition-fixing-the-problem/"],"uncertainty":"","worth_mentioning_reason":"","score_worth_mentioning":0,"score_solo_dev_relevance":0,"score_owner_work_relevance":0,"score_future_work_relevance":0,"score_decision_impact":0,"score_evidence_strength":2,"score_cost_time_leverage":0,"score_risk_reduction":0,"score_business_opportunity":0,"score_hype_risk":2,"score_novelty_penalty":3,"verdict":"reject","verdict_reason":"Infrastructure politics opinion piece; not actionable."}
]

payload = {
    "run_id": run_id,
    "private_memo": private_memo,
    "results": results
}

with open('/tmp/nl-completion-a8c77ab5.json', 'w') as f:
    json.dump(payload, f, ensure_ascii=False, indent=2)

print('Written', len(results), 'results to /tmp/nl-completion-a8c77ab5.json')
print('Verdicts:', {v: sum(1 for r in results if r['verdict']==v) for v in ['publish_public','publish_private','monitor','reject']})
