#!/usr/bin/env node
"use strict";

/**
 * build-site.js
 *
 * Reads dist/briefs/*.md (generated by social-generate.js) and writes a
 * static site to site/:
 *
 *   site/index.html                       archive landing page
 *   site/briefs/YYYY-MM-DD/index.html     individual brief pages
 *
 * No network access, no credentials, no paid integrations.
 * No dependencies beyond Node.js built-ins.
 *
 * Usage:
 *   node scripts/build-site.js [--dry-run]
 */

const fs = require("node:fs");
const path = require("node:path");
const {
  parseDailyReportMarkdown,
  parseLegacyReportMarkdown,
} = require("../src/report-archive.js");

const REPO_ROOT = path.join(__dirname, "..");
const BRIEFS_MD_DIR = path.join(REPO_ROOT, "dist", "briefs");
const REPORTS_MD_DIR = path.join(REPO_ROOT, "reports");
const LEGACY_RUNS_DIR = path.join(REPO_ROOT, "archive", "runs");
const SITE_DIR = path.join(REPO_ROOT, "site");
const SITE_BRIEFS_DIR = path.join(SITE_DIR, "briefs");
const SITE_REPORTS_DIR = path.join(SITE_DIR, "reports");

const DRY_RUN = process.argv.includes("--dry-run");

// ─── Helpers ──────────────────────────────────────────────────────────────────

function esc(str) {
  return String(str)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

/** Convert inline markdown links [text](url) → <a href="url">text</a> */
function inlineLinks(str) {
  return str.replace(/\[([^\]]+)\]\(([^)]+)\)/g, (_, text, href) => {
    return `<a href="${esc(href)}" target="_blank" rel="noopener">${esc(text)}</a>`;
  });
}

/** Convert a block of text: inline links + paragraph breaks */
function renderText(str) {
  return inlineLinks(esc(str).replace(/\n\n+/g, "<br><br>").replace(/\n/g, " "));
}

function formatDate(isoDate) {
  // "2026-05-21" → "May 21, 2026"
  try {
    const d = new Date(`${isoDate}T00:00:00Z`);
    return d.toLocaleDateString("en-US", { month: "long", day: "numeric", year: "numeric", timeZone: "UTC" });
  } catch {
    return isoDate;
  }
}

function formatDateShort(isoDate) {
  try {
    const d = new Date(`${isoDate}T00:00:00Z`);
    return d.toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric", timeZone: "UTC" });
  } catch {
    return isoDate;
  }
}

function write(filePath, content) {
  if (DRY_RUN) {
    console.log(`[dry-run] would write ${filePath} (${content.length} bytes)`);
    return;
  }
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, content, "utf8");
  console.log(`wrote ${path.relative(REPO_ROOT, filePath)}`);
}

function formatIsoDateTime(timestamp) {
  if (!timestamp) return "";
  const parsed = new Date(timestamp);
  if (Number.isNaN(parsed.getTime())) return timestamp;
  return parsed.toLocaleString("en-US", {
    year: "numeric",
    month: "short",
    day: "numeric",
    hour: "numeric",
    minute: "2-digit",
    timeZone: "America/New_York",
  });
}

function listLegacyBriefFiles() {
  if (!fs.existsSync(LEGACY_RUNS_DIR)) return [];

  return fs.readdirSync(LEGACY_RUNS_DIR, { withFileTypes: true })
    .filter((entry) => entry.isDirectory())
    .map((entry) => path.join(LEGACY_RUNS_DIR, entry.name, "brief.md"))
    .filter((filePath) => fs.existsSync(filePath))
    .sort();
}

// ─── Parser ───────────────────────────────────────────────────────────────────

/**
 * Parse a dist/briefs/YYYY-MM-DD.md file into a structured object.
 * Returns null and logs a warning if the file can't be parsed.
 */
function parseBriefMd(mdContent, date) {
  const lines = mdContent.split("\n");

  const brief = {
    date,
    title: "",
    status: "",
    mode: "",
    themes: [],
    leadTakeaway: "",
    published: [],   // { rank, title, sourceText, sourceUrl, category, published, facts, takeaway, uncertainty }
    monitored: [],
    allLinks: [],    // { tag, title, url }
    rejectedCount: 0,
  };

  // Parse the top-level title
  const titleLine = lines.find((l) => l.startsWith("# "));
  if (titleLine) brief.title = titleLine.replace(/^# /, "").trim();

  // Parse metadata fields (key: value lines near the top)
  for (const line of lines.slice(0, 15)) {
    if (line.startsWith("Date: ")) brief.date = line.replace("Date: ", "").trim();
    if (line.startsWith("Status: ")) brief.status = line.replace("Status: ", "").trim();
    if (line.startsWith("Mode: ")) brief.mode = line.replace("Mode: ", "").trim();
  }

  // Split into sections by "## "
  const sections = {};
  let currentSection = "_preamble";
  let sectionLines = [];

  for (const line of lines) {
    if (line.startsWith("## ")) {
      sections[currentSection] = sectionLines.join("\n");
      currentSection = line.replace(/^## /, "").trim().toLowerCase();
      sectionLines = [];
    } else {
      sectionLines.push(line);
    }
  }
  sections[currentSection] = sectionLines.join("\n");

  // Parse daily summary section
  const summary = sections["daily summary"] || "";
  const themeLine = summary.split("\n").find((l) => l.startsWith("Themes:"));
  if (themeLine) {
    brief.themes = themeLine
      .replace("Themes:", "")
      .replace(/\.$/, "")
      .split("•")
      .map((t) => t.trim())
      .filter(Boolean);
  }
  // Lead takeaway is the first non-empty, non-themes line after themes
  const summaryLines = summary.split("\n").filter((l) => l.trim() && !l.startsWith("Themes:"));
  if (summaryLines[0]) brief.leadTakeaway = summaryLines[0].trim();

  // Parser helper for item blocks (used by both "worth mentioning" and "monitor")
  function parseItems(sectionText) {
    const items = [];
    // Split by "### N. " item headers
    const itemBlocks = sectionText.split(/\n(?=### \d+\.)/).filter((b) => b.trim());

    for (const block of itemBlocks) {
      const itemLines = block.split("\n");
      const headerLine = itemLines.find((l) => l.startsWith("### "));
      if (!headerLine) continue;

      const rankMatch = headerLine.match(/^### (\d+)\.\s+(.+)$/);
      const item = {
        rank: rankMatch ? parseInt(rankMatch[1], 10) : 0,
        title: rankMatch ? rankMatch[2].trim() : headerLine.replace(/^### /, "").trim(),
        sourceText: "",
        sourceUrl: "",
        category: "",
        published: "",
        facts: [],
        takeaway: "",
        uncertainty: "",
      };

      let inFacts = false;
      for (const line of itemLines.slice(1)) {
        const trimmed = line.trim();

        if (trimmed.startsWith("- Source:")) {
          // "- Source: [name](url)" or "- Source: name"
          const linkMatch = trimmed.match(/\[([^\]]+)\]\(([^)]+)\)/);
          if (linkMatch) {
            item.sourceText = linkMatch[1];
            item.sourceUrl = linkMatch[2];
          } else {
            item.sourceText = trimmed.replace("- Source:", "").trim();
          }
          inFacts = false;
        } else if (trimmed.startsWith("- Category:")) {
          item.category = trimmed.replace("- Category:", "").trim();
          inFacts = false;
        } else if (trimmed.startsWith("- Published:")) {
          item.published = trimmed.replace("- Published:", "").trim().slice(0, 10);
          inFacts = false;
        } else if (trimmed === "Source facts:") {
          inFacts = true;
        } else if (inFacts && trimmed.startsWith("- ")) {
          item.facts.push(trimmed.replace(/^- /, ""));
        } else if (trimmed.startsWith("Builder/operator takeaway:")) {
          item.takeaway = trimmed.replace("Builder/operator takeaway:", "").trim();
          inFacts = false;
        } else if (trimmed.startsWith("Uncertainty:")) {
          item.uncertainty = trimmed.replace("Uncertainty:", "").trim();
          inFacts = false;
        } else if (trimmed && !trimmed.startsWith("- Labels:") && !trimmed.startsWith("- Product relevance:")) {
          // Continuation of takeaway (multi-line)
          if (item.takeaway && !inFacts) {
            item.takeaway += " " + trimmed;
          }
        }
      }

      items.push(item);
    }
    return items;
  }

  // Parse "worth mentioning" section
  const worthSection = sections["worth mentioning"] || "";
  brief.published = parseItems(worthSection);

  // Parse "monitor" section
  const monitorSection = sections["monitor (keep an eye on it)"] || sections["monitor"] || "";
  brief.monitored = parseItems(monitorSection);

  // Parse "all researched links" section
  const linksSection = sections["all researched links (complete index)"] || sections["all researched links"] || "";
  for (const line of linksSection.split("\n")) {
    const linkMatch = line.match(/^- \[([PMR])\] \[([^\]]+)\]\(([^)]+)\)/);
    if (linkMatch) {
      brief.allLinks.push({ tag: linkMatch[1], title: linkMatch[2], url: linkMatch[3] });
    }
  }

  // Parse rejected count
  const rejectedSection = sections["rejected items (not recommended)"] || sections["rejected items"] || "";
  const rejectedMatch = rejectedSection.match(/Rejected:\s*(\d+)/);
  if (rejectedMatch) brief.rejectedCount = parseInt(rejectedMatch[1], 10);

  return brief;
}

// ─── CSS ──────────────────────────────────────────────────────────────────────

const SHARED_CSS = `
  *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }

  :root {
    --bg:        #0e0f13;
    --bg2:       #15161c;
    --bg3:       #1d1f28;
    --border:    #2a2d3a;
    --text:      #d8d9e0;
    --text-dim:  #888a96;
    --accent:    #f0c040;
    --accent2:   #e87c3e;
    --link:      #7eb8f0;
    --tag-p:     #3a6644;
    --tag-m:     #4a4a22;
    --tag-r:     #2a2a2a;
  }

  html { font-size: 16px; }

  body {
    background: var(--bg);
    color: var(--text);
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", system-ui, sans-serif;
    line-height: 1.65;
    min-height: 100vh;
  }

  a { color: var(--link); text-decoration: none; }
  a:hover { text-decoration: underline; }

  .site-header {
    border-bottom: 1px solid var(--border);
    padding: 1.5rem 1.5rem 1.25rem;
    display: flex;
    align-items: baseline;
    gap: 1.25rem;
    flex-wrap: wrap;
  }

  .brand {
    font-family: "Georgia", "Times New Roman", serif;
    font-size: 1.2rem;
    font-weight: normal;
    letter-spacing: 0.04em;
    color: var(--accent);
    text-transform: uppercase;
    text-decoration: none;
  }
  .brand:hover { text-decoration: none; opacity: 0.85; }

  .brand-tagline {
    font-size: 0.8rem;
    color: var(--text-dim);
    letter-spacing: 0.02em;
  }

  .site-nav {
    margin-left: auto;
    font-size: 0.8rem;
    display: flex;
    gap: 1.25rem;
    align-items: center;
  }
  .site-nav a { color: var(--text-dim); }
  .site-nav a:hover { color: var(--text); text-decoration: none; }

  main { max-width: 760px; margin: 0 auto; padding: 2.5rem 1.5rem 4rem; }

  h1 { font-size: 1.5rem; font-weight: 600; line-height: 1.3; color: #fff; }
  h2 { font-size: 1rem; font-weight: 600; letter-spacing: 0.06em; text-transform: uppercase;
       color: var(--text-dim); margin-top: 2.5rem; margin-bottom: 1rem;
       padding-bottom: 0.4rem; border-bottom: 1px solid var(--border); }
  h3 { font-size: 1rem; font-weight: 600; color: #fff; }

  p { margin-top: 0.75rem; }

  .meta { font-size: 0.78rem; color: var(--text-dim); margin-top: 0.3rem; }
  .meta span + span::before { content: " · "; }

  .tag {
    display: inline-block;
    font-size: 0.68rem;
    font-weight: 600;
    letter-spacing: 0.06em;
    text-transform: uppercase;
    padding: 0.15em 0.5em;
    border-radius: 3px;
    vertical-align: middle;
  }
  .tag-p { background: var(--tag-p); color: #8ecf9e; }
  .tag-m { background: var(--tag-m); color: #c8c870; }
  .tag-r { background: var(--tag-r); color: var(--text-dim); }

  .item {
    padding: 1.25rem 0;
    border-bottom: 1px solid var(--border);
  }
  .item:last-child { border-bottom: none; }

  .item-title { font-size: 1rem; font-weight: 600; color: #fff; line-height: 1.35; }
  .item-title a { color: inherit; }
  .item-title a:hover { color: var(--accent); text-decoration: none; }

  .item-takeaway {
    margin-top: 0.6rem;
    font-size: 0.92rem;
    line-height: 1.6;
    color: var(--text);
  }

  .item-facts {
    margin-top: 0.5rem;
    font-size: 0.84rem;
    color: var(--text-dim);
    border-left: 2px solid var(--border);
    padding-left: 0.75rem;
    line-height: 1.55;
  }

  .item-uncertainty {
    margin-top: 0.4rem;
    font-size: 0.8rem;
    color: var(--accent2);
    font-style: italic;
  }

  .item-meta {
    margin-top: 0.5rem;
    font-size: 0.75rem;
    color: var(--text-dim);
    display: flex;
    gap: 0.75rem;
    flex-wrap: wrap;
    align-items: center;
  }

  details { margin-top: 1rem; }
  details summary {
    cursor: pointer;
    font-size: 0.8rem;
    color: var(--text-dim);
    user-select: none;
    padding: 0.4rem 0;
  }
  details summary:hover { color: var(--text); }
  details[open] summary { color: var(--text); }

  .link-index {
    margin-top: 0.75rem;
    font-size: 0.8rem;
    line-height: 1.8;
  }
  .link-index a { color: var(--text-dim); }
  .link-index a:hover { color: var(--link); }
  .link-index .li-p a { color: var(--text); }

  .back-link {
    display: inline-block;
    font-size: 0.8rem;
    color: var(--text-dim);
    margin-bottom: 2rem;
  }
  .back-link:hover { color: var(--text); text-decoration: none; }
  .back-link::before { content: "← "; }

  .summary-card {
    margin-top: 1.25rem;
    padding: 1.1rem 1.15rem;
    background: linear-gradient(180deg, rgba(240, 192, 64, 0.08), rgba(240, 192, 64, 0.02));
    border: 1px solid rgba(240, 192, 64, 0.18);
    border-radius: 10px;
  }

  .summary-card p {
    margin-top: 0.35rem;
    font-size: 0.95rem;
    line-height: 1.65;
  }

  .eyebrow {
    font-size: 0.72rem;
    text-transform: uppercase;
    letter-spacing: 0.1em;
    color: var(--accent);
    font-weight: 700;
  }

  .raw-report {
    margin-top: 0.9rem;
    white-space: pre-wrap;
    font-family: ui-monospace, SFMono-Regular, Menlo, monospace;
    font-size: 0.78rem;
    line-height: 1.65;
    color: var(--text-dim);
    background: var(--bg2);
    border: 1px solid var(--border);
    border-radius: 8px;
    padding: 1rem;
  }

  .item-stack {
    display: grid;
    gap: 0.85rem;
  }

  .compact-list {
    margin-top: 0.75rem;
    display: grid;
    gap: 0.8rem;
  }

  .compact-list .item {
    padding: 0.9rem 0;
  }

  footer {
    border-top: 1px solid var(--border);
    padding: 1.5rem;
    font-size: 0.78rem;
    color: var(--text-dim);
    text-align: center;
    line-height: 1.8;
  }
`;

function siteNav(active = "") {
  const items = [
    { href: "/", label: "Archive", key: "archive" },
    { href: "/reports/", label: "Reports", key: "reports" },
  ];

  return items.map((item) => {
    const style = item.key === active ? ` style="color:#fff"` : "";
    return `<a href="${item.href}"${style}>${item.label}</a>`;
  }).join("");
}

function renderRawMarkdown(markdown) {
  return `<details>
      <summary>Original markdown</summary>
      <pre class="raw-report">${esc(markdown)}</pre>
    </details>`;
}

// ─── Brief page renderer ──────────────────────────────────────────────────────

function renderBriefPage(brief) {
  const dateLabel = formatDate(brief.date);
  const published = brief.published;
  const monitored = brief.monitored;

  function renderItem(item) {
    const sourceLink = item.sourceUrl
      ? `<a href="${esc(item.sourceUrl)}" target="_blank" rel="noopener">${esc(item.sourceText || item.sourceUrl)}</a>`
      : esc(item.sourceText || "");

    const titleEl = item.sourceUrl
      ? `<a href="${esc(item.sourceUrl)}" target="_blank" rel="noopener">${esc(item.title)}</a>`
      : esc(item.title);

    const factsHtml = item.facts.length
      ? `<div class="item-facts">${item.facts.map((f) => `<div>${renderText(f)}</div>`).join("")}</div>`
      : "";

    const uncertaintyHtml = item.uncertainty
      ? `<div class="item-uncertainty">⚠ Uncertainty: ${renderText(item.uncertainty)}</div>`
      : "";

    return `
    <div class="item">
      <div class="item-title">${titleEl}</div>
      ${item.takeaway ? `<div class="item-takeaway">${renderText(item.takeaway)}</div>` : ""}
      ${factsHtml}
      ${uncertaintyHtml}
      <div class="item-meta">
        ${sourceLink ? `<span>${sourceLink}</span>` : ""}
        ${item.category ? `<span>${esc(item.category)}</span>` : ""}
        ${item.published ? `<span>${esc(item.published)}</span>` : ""}
      </div>
    </div>`;
  }

  const publishedHtml = published.length
    ? `<h2>Worth mentioning</h2>\n${published.map(renderItem).join("\n")}`
    : "";

  const monitoredHtml = monitored.length
    ? `<h2>Monitor</h2>\n${monitored.map(renderItem).join("\n")}`
    : "";

  const linkIndex = brief.allLinks.length
    ? `<details>
      <summary>${brief.allLinks.length} researched links (full index)</summary>
      <div class="link-index">
        ${brief.allLinks.map((l) => {
          const cls = `li-${l.tag.toLowerCase()}`;
          return `<div class="${cls}"><span class="tag tag-${l.tag.toLowerCase()}">${esc(l.tag)}</span> <a href="${esc(l.url)}" target="_blank" rel="noopener">${esc(l.title)}</a></div>`;
        }).join("\n        ")}
      </div>
    </details>`
    : "";

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>${esc(brief.title)} — The Nightly Librarian</title>
  <meta name="description" content="${esc(brief.leadTakeaway || brief.title)}">
  <style>${SHARED_CSS}</style>
</head>
<body>
  <header class="site-header">
    <a class="brand" href="/">The Nightly Librarian</a>
    <span class="brand-tagline">AI signal without the noise</span>
    <nav class="site-nav">${siteNav("archive")}</nav>
  </header>
  <main>
    <a class="back-link" href="/">All briefs</a>
    <h1>${esc(dateLabel)}</h1>
    <div class="meta">
      ${brief.themes.length ? `<span>${brief.themes.join(" · ")}</span>` : ""}
      ${brief.mode && brief.mode !== "primary" ? `<span>${esc(brief.mode)} mode</span>` : ""}
    </div>

    ${brief.leadTakeaway ? `<p style="margin-top:1.25rem;font-size:1.05rem;line-height:1.65;">${renderText(brief.leadTakeaway)}</p>` : ""}

    ${publishedHtml}
    ${monitoredHtml}
    ${linkIndex}
  </main>
  <footer>
    The Nightly Librarian — what changed, why it matters, what to do about it.<br>
    <a href="/">← Back to archive</a>
  </footer>
</body>
</html>
`;
}

// ─── Report renderers ──────────────────────────────────────────────────────────

function renderDailyReportPage(report) {
  const worthAttentionHtml = report.worthAttention.length
    ? `<h2>Worth attention</h2>
    <div class="item-stack">
      ${report.worthAttention.map((item) => `
      <div class="item">
        <div class="item-title">${item.url ? `<a href="${esc(item.url)}" target="_blank" rel="noopener">${esc(item.title)}</a>` : esc(item.title)}</div>
        ${item.summary ? `<div class="item-takeaway">${renderText(item.summary)}</div>` : ""}
      </div>`).join("\n")}
    </div>`
    : "";

  const digestHtml = report.fullDigest.length
    ? `<h2>Full digest</h2>
    <div class="compact-list">
      ${report.fullDigest.map((item) => `
      <div class="item">
        <div class="item-title">
          <span class="tag tag-${esc(item.tag.toLowerCase())}">${esc(item.tag)}</span>
          ${item.url ? `<a href="${esc(item.url)}" target="_blank" rel="noopener">${esc(item.title)}</a>` : esc(item.title)}
        </div>
        ${item.summary ? `<div class="item-takeaway">${renderText(item.summary)}</div>` : ""}
        <div class="item-meta">
          ${item.source ? `<span>${esc(item.source)}</span>` : ""}
        </div>
      </div>`).join("\n")}
    </div>`
    : "";

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>${esc(report.date)} report log — The Nightly Librarian</title>
  <meta name="description" content="${esc(report.summary.text)}">
  <style>${SHARED_CSS}</style>
</head>
<body>
  <header class="site-header">
    <a class="brand" href="/">The Nightly Librarian</a>
    <span class="brand-tagline">AI signal without the noise</span>
    <nav class="site-nav">${siteNav("reports")}</nav>
  </header>
  <main>
    <a class="back-link" href="/reports/">All reports</a>
    <h1>${esc(formatDate(report.date))}</h1>
    <div class="meta">
      ${report.completedAt ? `<span>${esc(formatIsoDateTime(report.completedAt))}</span>` : ""}
      ${report.runId ? `<span>run ${esc(report.runId.slice(0, 8))}</span>` : ""}
    </div>
    <div class="summary-card">
      <div class="eyebrow">Report Summary</div>
      <p>${esc(report.summary.text)}</p>
      <div class="meta">
        ${report.summary.stats.map((item) => `<span>${esc(item)}</span>`).join("")}
      </div>
    </div>
    ${worthAttentionHtml}
    ${digestHtml}
    ${renderRawMarkdown(report.rawMarkdown)}
  </main>
  <footer>
    Nightly report log for the Codex morning memo workflow.<br>
    <a href="/reports/">← Back to reports</a>
  </footer>
</body>
</html>
`;
}

function renderLegacyReportPage(report) {
  const signalsHtml = report.signals.length
    ? `<h2>Signals</h2>
    <div class="item-stack">
      ${report.signals.map((item, index) => `
      <div class="item">
        <div class="item-title">${index + 1}. ${esc(item.title)}</div>
        ${item.body ? `<div class="item-takeaway">${renderText(item.body)}</div>` : ""}
      </div>`).join("\n")}
    </div>`
    : "";

  const tryThisHtml = report.tryThis
    ? `<h2>Try this</h2><div class="item"><div class="item-takeaway">${renderText(report.tryThis)}</div></div>`
    : "";

  const verdictHtml = report.verdict
    ? `<h2>Librarian's verdict</h2><div class="item"><div class="item-takeaway">${renderText(report.verdict)}</div></div>`
    : "";

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>${esc(report.date)} legacy archive — The Nightly Librarian</title>
  <meta name="description" content="${esc(report.summary.text)}">
  <style>${SHARED_CSS}</style>
</head>
<body>
  <header class="site-header">
    <a class="brand" href="/">The Nightly Librarian</a>
    <span class="brand-tagline">AI signal without the noise</span>
    <nav class="site-nav">${siteNav("reports")}</nav>
  </header>
  <main>
    <a class="back-link" href="/reports/">All reports</a>
    <h1>${esc(formatDate(report.date))}</h1>
    <div class="meta">
      <span>${esc(report.issue || "Legacy archive")}</span>
      <span>${esc(report.slug)}</span>
    </div>
    <div class="summary-card">
      <div class="eyebrow">Archive Summary</div>
      <p>${esc(report.summary.text)}</p>
      <div class="meta">
        ${report.summary.stats.map((item) => `<span>${esc(item)}</span>`).join("")}
      </div>
    </div>
    ${signalsHtml}
    ${tryThisHtml}
    ${verdictHtml}
    ${renderRawMarkdown(report.rawMarkdown)}
  </main>
  <footer>
    Legacy Nightly Librarian archive snapshot.<br>
    <a href="/reports/">← Back to reports</a>
  </footer>
</body>
</html>
`;
}

function renderReportsIndexPage(reports, legacyReports) {
  const sortedReports = [...reports].sort((a, b) => b.date.localeCompare(a.date));
  const sortedLegacyReports = [...legacyReports].sort((a, b) => b.slug.localeCompare(a.slug));

  const recentRows = sortedReports.map((report) => `
    <div class="item">
      <div class="item-title"><a href="/reports/${esc(report.slug)}/">${esc(formatDate(report.date))}</a></div>
      <div class="item-takeaway">${renderText(report.summary.text)}</div>
      <div class="item-meta">
        ${report.summary.stats.map((item) => `<span>${esc(item)}</span>`).join("")}
      </div>
    </div>`).join("\n");

  const legacyRows = sortedLegacyReports.map((report) => `
    <div class="item">
      <div class="item-title"><a href="/reports/legacy/${esc(report.slug)}/">${esc(formatDate(report.date))}</a></div>
      <div class="item-takeaway">${renderText(report.summary.text)}</div>
      <div class="item-meta">
        <span>${esc(report.issue || "Legacy archive")}</span>
        <span>${esc(report.slug)}</span>
      </div>
    </div>`).join("\n");

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Reports — The Nightly Librarian</title>
  <meta name="description" content="Codex morning memo report log and legacy Nightly Librarian archive entries.">
  <style>${SHARED_CSS}</style>
</head>
<body>
  <header class="site-header">
    <a class="brand" href="/">The Nightly Librarian</a>
    <span class="brand-tagline">AI signal without the noise</span>
    <nav class="site-nav">${siteNav("reports")}</nav>
  </header>
  <main>
    <h1>Report Log</h1>
    <p style="margin-top:0.75rem;font-size:0.95rem;color:var(--text-dim);line-height:1.6;max-width:620px;">Nightly report drafts from the Codex morning memo workflow, plus preserved legacy archive snapshots from the earlier issue format.</p>
    ${reports.length ? `<h2>Recent reports</h2>${recentRows}` : ""}
    ${legacyReports.length ? `<h2>Legacy archive</h2>${legacyRows}` : ""}
  </main>
  <footer>
    The report log preserves the long-form editorial trace behind the public brief pages.
  </footer>
</body>
</html>
`;
}

// ─── Index page renderer ──────────────────────────────────────────────────────

function renderIndexPage(briefs, reports, legacyReports) {
  // briefs sorted newest-first
  const sorted = [...briefs].sort((a, b) => b.date.localeCompare(a.date));
  const latest = sorted[0];
  const sortedLegacyReports = [...legacyReports].sort((a, b) => b.slug.localeCompare(a.slug));

  function renderArchiveRow(brief) {
    const lead = brief.published[0];
    return `
    <div class="item">
      <div class="item-title">
        <a href="/briefs/${esc(brief.date)}/">${esc(formatDateShort(brief.date))}</a>
        ${brief.themes.length ? ` <span class="meta" style="font-weight:normal;font-size:0.8rem;">${brief.themes.join(" · ")}</span>` : ""}
      </div>
      ${lead ? `<div class="item-takeaway" style="font-size:0.88rem;">${renderText(lead.takeaway || lead.title)}</div>` : ""}
      <div class="item-meta">
        <span>${brief.published.length} item${brief.published.length !== 1 ? "s" : ""}</span>
        ${brief.monitored.length ? `<span>${brief.monitored.length} to watch</span>` : ""}
        ${brief.allLinks.length ? `<span>${brief.allLinks.length} links researched</span>` : ""}
      </div>
    </div>`;
  }

  // Hero block for latest brief
  const heroHtml = latest ? `
  <div style="margin-top:2.5rem;padding:1.5rem;background:var(--bg2);border:1px solid var(--border);border-radius:6px;">
    <div class="meta" style="margin-bottom:0.5rem;">Latest · ${esc(formatDate(latest.date))}</div>
    <h1 style="font-size:1.15rem;">${latest.themes.length ? esc(latest.themes.join(" · ")) : "Today's brief"}</h1>
    ${latest.leadTakeaway ? `<p style="margin-top:0.75rem;font-size:0.95rem;line-height:1.6;">${renderText(latest.leadTakeaway)}</p>` : ""}
    <div style="margin-top:1rem;">
      <a href="/briefs/${esc(latest.date)}/" style="font-size:0.88rem;color:var(--accent);font-weight:600;">Read the full brief →</a>
    </div>
  </div>` : "";

  const archiveRows = sorted.slice(1).map(renderArchiveRow).join("\n");
  const archiveSectionHtml = sorted.length > 1
    ? `<h2>Archive</h2>\n${archiveRows}`
    : "";

  const latestReport = reports[0] || sortedLegacyReports[0] || null;
  const reportsHtml = latestReport
    ? `<h2>Report log</h2>
    <div class="item">
      <div class="item-title">
        <a href="${reports[0] ? `/reports/${esc(latestReport.slug)}/` : `/reports/legacy/${esc(latestReport.slug)}/`}">${reports[0] ? `Latest report · ${esc(formatDate(latestReport.date))}` : `Legacy archive · ${esc(formatDate(latestReport.date))}`}</a>
      </div>
      <div class="item-takeaway">${renderText(latestReport.summary.text)}</div>
      <div class="item-meta">
        <span>${reports.length} recent report${reports.length === 1 ? "" : "s"}</span>
        ${legacyReports.length ? `<span>${legacyReports.length} legacy archive entr${legacyReports.length === 1 ? "y" : "ies"}</span>` : ""}
      </div>
    </div>
    <div style="margin-top:0.85rem;">
      <a href="/reports/" style="font-size:0.88rem;color:var(--accent);font-weight:600;">Browse all reports →</a>
    </div>`
    : "";

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>The Nightly Librarian — AI signal without the noise</title>
  <meta name="description" content="Daily AI and dev intelligence for builders and operators. What changed, why it matters, what to do about it.">
  <style>${SHARED_CSS}

  .hero-tagline {
    font-size: 1.35rem;
    line-height: 1.4;
    color: #fff;
    font-weight: 600;
    margin-top: 2.5rem;
  }
  .hero-sub {
    font-size: 0.95rem;
    color: var(--text-dim);
    margin-top: 0.6rem;
    line-height: 1.6;
    max-width: 560px;
  }
  </style>
</head>
<body>
  <header class="site-header">
    <a class="brand" href="/">The Nightly Librarian</a>
    <span class="brand-tagline">AI signal without the noise</span>
    <nav class="site-nav">${siteNav("archive")}</nav>
  </header>
  <main>
    <p class="hero-tagline">What changed. Why it matters.<br>What builders should do about it.</p>
    <p class="hero-sub">Daily AI and dev intelligence for builders, operators, and technical founders.
    No hype, no enterprise filler — just what matters for people who ship.</p>

    ${heroHtml}
    ${reportsHtml}
    ${archiveSectionHtml}
  </main>
  <footer>
    The Nightly Librarian — built for builders, not boardrooms.
  </footer>
</body>
</html>
`;
}

// ─── Main ─────────────────────────────────────────────────────────────────────

function main() {
  if (!fs.existsSync(BRIEFS_MD_DIR)) {
    console.error(`dist/briefs/ not found at ${BRIEFS_MD_DIR}`);
    process.exit(1);
  }

  const mdFiles = fs.readdirSync(BRIEFS_MD_DIR)
    .filter((f) => /^\d{4}-\d{2}-\d{2}\.md$/.test(f))
    .sort();

  if (!mdFiles.length) {
    console.error("No brief markdown files found in dist/briefs/");
    process.exit(1);
  }

  const briefs = [];
  const reports = [];
  const legacyReports = [];

  for (const filename of mdFiles) {
    const date = filename.replace(".md", "");
    const mdPath = path.join(BRIEFS_MD_DIR, filename);
    const content = fs.readFileSync(mdPath, "utf8");
    const brief = parseBriefMd(content, date);
    if (!brief) continue;

    briefs.push(brief);

    // Write individual brief page
    const briefPagePath = path.join(SITE_BRIEFS_DIR, date, "index.html");
    write(briefPagePath, renderBriefPage(brief));
  }

  if (fs.existsSync(REPORTS_MD_DIR)) {
    const reportFiles = fs.readdirSync(REPORTS_MD_DIR)
      .filter((file) => /^\d{4}-\d{2}-\d{2}\.md$/.test(file))
      .sort()
      .reverse();

    for (const filename of reportFiles) {
      const date = filename.replace(".md", "");
      const filePath = path.join(REPORTS_MD_DIR, filename);
      const report = parseDailyReportMarkdown(fs.readFileSync(filePath, "utf8"), date);
      reports.push(report);
      write(path.join(SITE_REPORTS_DIR, date, "index.html"), renderDailyReportPage(report));
    }
  }

  for (const filePath of listLegacyBriefFiles()) {
    const slug = path.basename(path.dirname(filePath));
    const legacy = parseLegacyReportMarkdown(fs.readFileSync(filePath, "utf8"), slug);
    if (!legacy) continue;
    legacyReports.push(legacy);
    write(path.join(SITE_REPORTS_DIR, "legacy", slug, "index.html"), renderLegacyReportPage(legacy));
  }

  // Write index page
  write(path.join(SITE_DIR, "index.html"), renderIndexPage(briefs, reports, legacyReports));
  write(path.join(SITE_REPORTS_DIR, "index.html"), renderReportsIndexPage(reports, legacyReports));

  console.log(`\nBuild complete. ${briefs.length} brief(s), ${reports.length} report(s), ${legacyReports.length} legacy archive entr${legacyReports.length === 1 ? "y" : "ies"} → site/`);
  if (DRY_RUN) console.log("(dry run — no files written)");
}

main();
