#!/usr/bin/env node
"use strict";

/**
 * build-site.js
 *
 * Reads dist/briefs/*.md (generated by social-generate.js) and writes a
 * static site to site/:
 *
 *   site/index.html                       archive landing page
 *   site/briefs/YYYY-MM-DD/index.html     individual brief pages
 *
 * No network access, no credentials, no paid integrations.
 * No dependencies beyond Node.js built-ins.
 *
 * Usage:
 *   node scripts/build-site.js [--dry-run]
 */

const fs = require("node:fs");
const path = require("node:path");
const {
  parseDailyReportMarkdown,
  parseLegacyReportMarkdown,
} = require("../src/report-archive.js");

const REPO_ROOT = path.join(__dirname, "..");

// Load .env if present (no dotenv dependency — plain parse)
const envPath = path.join(REPO_ROOT, ".env");
if (fs.existsSync(envPath)) {
  fs.readFileSync(envPath, "utf8").split(/\r?\n/).forEach((line) => {
    const m = line.match(/^\s*([A-Z_][A-Z0-9_]*)\s*=\s*(.*)\s*$/);
    if (m && !process.env[m[1]]) process.env[m[1]] = m[2].replace(/^['"]|['"]$/g, "");
  });
}
const BRIEFS_MD_DIR = path.join(REPO_ROOT, "dist", "briefs");
const REPORTS_MD_DIR = path.join(REPO_ROOT, "reports");
const LEGACY_RUNS_DIR = path.join(REPO_ROOT, "archive", "runs");
const SITE_DIR = path.join(REPO_ROOT, "site");
const SITE_BRIEFS_DIR = path.join(SITE_DIR, "briefs");
const SITE_REPORTS_DIR = path.join(SITE_DIR, "reports");

const DRY_RUN = process.argv.includes("--dry-run");

// ─── Site config ──────────────────────────────────────────────────────────────
const SITE_URL = process.env.NIGHTLY_LIBRARIAN_PUBLIC_BASE_URL || process.env.SITE_URL || "https://thenightlylibrarian.com";
const SITE_NAME = "The Nightly Librarian";
const SITE_DESCRIPTION = "Daily AI and dev intelligence for builders and operators. What changed, why it matters, what to do about it.";

// Substack publication slug — replace YOUR_SLUG with your real slug, e.g. "nightlylibrarian"
// Your subscribe page lives at https://YOUR_SLUG.substack.com/subscribe
const SUBSTACK_SLUG = process.env.SUBSTACK_SLUG || "YOUR_SLUG";

// ─── Helpers ──────────────────────────────────────────────────────────────────

function esc(str) {
  return String(str)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

/**
 * Render the full SEO <head> block: canonical, OG, Twitter Card, JSON-LD, RSS autodiscovery.
 * @param {{ title: string, description: string, path: string, type?: string, publishedDate?: string }} opts
 */
// Placeholder og-image — replace site/og-image.png with a real 1200x630 PNG.
// TODO: add sameAs to Blog schema once X/LinkedIn handles are confirmed.
const OG_IMAGE = `${SITE_URL}/og-image.png`;

function truncateDesc(str) {
  const raw = str.slice(0, 155);
  const m = raw.match(/^([\s\S]*[.!?])/);
  if (m && m[1].length > 40) return m[1].trim();
  const lastSpace = raw.lastIndexOf(" ");
  return (lastSpace > 40 ? raw.slice(0, lastSpace) : raw).trim();
}

function seoMeta({ title, description, path: urlPath, type = "website", publishedDate = "", leadTitle = "" }) {
  const fullUrl = SITE_URL + urlPath;
  const fullTitle = title === SITE_NAME ? title : `${title} | ${SITE_NAME}`;
  const safeDesc = esc(truncateDesc(description));
  const safeTitle = esc(fullTitle);
  const safeUrl = esc(fullUrl);
  const safeOgImage = esc(OG_IMAGE);

  const jsonLd = type === "article"
    ? JSON.stringify({
        "@context": "https://schema.org",
        "@type": "NewsArticle",
        "headline": leadTitle || title,
        "description": description.slice(0, 500),
        "url": fullUrl,
        "publisher": { "@type": "Organization", "name": SITE_NAME, "url": SITE_URL },
        ...(publishedDate ? { "datePublished": publishedDate, "dateModified": publishedDate } : {}),
      })
    : JSON.stringify([
        {
          "@context": "https://schema.org",
          "@type": "WebSite",
          "name": SITE_NAME,
          "url": SITE_URL,
          "description": SITE_DESCRIPTION,
        },
        {
          "@context": "https://schema.org",
          "@type": "Blog",
          "name": SITE_NAME,
          "url": SITE_URL,
          "description": SITE_DESCRIPTION,
          "author": { "@type": "Person", "name": "The Nightly Librarian" },
        },
      ]);

  return `  <meta name="description" content="${safeDesc}">
  <link rel="canonical" href="${safeUrl}">
  <link rel="alternate" type="application/rss+xml" title="${esc(SITE_NAME)}" href="${esc(SITE_URL)}/feed.xml">
  <meta property="og:type" content="${esc(type === "article" ? "article" : "website")}">
  <meta property="og:site_name" content="${esc(SITE_NAME)}">
  <meta property="og:title" content="${safeTitle}">
  <meta property="og:description" content="${safeDesc}">
  <meta property="og:url" content="${safeUrl}">
  <meta property="og:image" content="${safeOgImage}">
  <meta property="og:image:width" content="1200">
  <meta property="og:image:height" content="630">
  <meta name="twitter:card" content="summary_large_image">
  <meta name="twitter:title" content="${safeTitle}">
  <meta name="twitter:description" content="${safeDesc}">
  <meta name="twitter:image" content="${safeOgImage}">
  <script type="application/ld+json">${jsonLd}</script>`;
}

/**
 * Sidebar subscribe block — compact email form for the sidebar.
 */
function subscribeSidebar() {
  const action = `https://${SUBSTACK_SLUG}.substack.com/subscribe`;
  return `<div class="sidebar-block">
          <div class="section-label">Get the brief</div>
          <p class="subscribe-desc">Every morning. No hype, no filler.</p>
          <form class="subscribe-form" action="${action}" method="GET" target="_blank">
            <input class="subscribe-input" type="email" name="email" placeholder="your@email.com" required>
            <button class="subscribe-btn" type="submit">Subscribe →</button>
          </form>
          <p class="subscribe-note">Free. Unsubscribe any time.</p>
        </div>`;
}

/**
 * Bottom-of-brief subscribe strip — slightly more expansive CTA after the content.
 */
function subscribeStrip() {
  const action = `https://${SUBSTACK_SLUG}.substack.com/subscribe`;
  return `<div class="subscribe-strip">
      <div class="subscribe-headline">Get this every morning</div>
      <p class="subscribe-desc">Filtered from 40+ sources daily — what changed, why it matters, what to do. Free.</p>
      <form class="subscribe-form" action="${action}" method="GET" target="_blank">
        <input class="subscribe-input" type="email" name="email" placeholder="your@email.com" required>
        <button class="subscribe-btn" type="submit">Subscribe →</button>
      </form>
      <p class="subscribe-note">Free. Unsubscribe any time.</p>
    </div>`;
}

/** Convert inline markdown links [text](url) → <a href="url">text</a> */
function inlineLinks(str) {
  return str.replace(/\[([^\]]+)\]\(([^)]+)\)/g, (_, text, href) => {
    return `<a href="${esc(href)}" target="_blank" rel="noopener">${esc(text)}</a>`;
  });
}

/** Convert a block of text: inline links + paragraph breaks */
function renderText(str) {
  return inlineLinks(esc(str).replace(/\n\n+/g, "<br><br>").replace(/\n/g, " "));
}

function formatDate(isoDate) {
  // "2026-05-21" → "May 21, 2026"
  try {
    const d = new Date(`${isoDate}T00:00:00Z`);
    return d.toLocaleDateString("en-US", { month: "long", day: "numeric", year: "numeric", timeZone: "UTC" });
  } catch {
    return isoDate;
  }
}

function formatDateShort(isoDate) {
  try {
    const d = new Date(`${isoDate}T00:00:00Z`);
    return d.toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric", timeZone: "UTC" });
  } catch {
    return isoDate;
  }
}

function write(filePath, content) {
  if (DRY_RUN) {
    console.log(`[dry-run] would write ${filePath} (${content.length} bytes)`);
    return;
  }
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, content, "utf8");
  console.log(`wrote ${path.relative(REPO_ROOT, filePath)}`);
}

function formatIsoDateTime(timestamp) {
  if (!timestamp) return "";
  const parsed = new Date(timestamp);
  if (Number.isNaN(parsed.getTime())) return timestamp;
  return parsed.toLocaleString("en-US", {
    year: "numeric",
    month: "short",
    day: "numeric",
    hour: "numeric",
    minute: "2-digit",
    timeZone: "America/New_York",
  });
}

function listLegacyBriefFiles() {
  if (!fs.existsSync(LEGACY_RUNS_DIR)) return [];

  return fs.readdirSync(LEGACY_RUNS_DIR, { withFileTypes: true })
    .filter((entry) => entry.isDirectory())
    .map((entry) => path.join(LEGACY_RUNS_DIR, entry.name, "brief.md"))
    .filter((filePath) => fs.existsSync(filePath))
    .sort();
}

// ─── Parser ───────────────────────────────────────────────────────────────────

/**
 * Parse a dist/briefs/YYYY-MM-DD.md file into a structured object.
 * Returns null and logs a warning if the file can't be parsed.
 */
function parseBriefMd(mdContent, date) {
  const lines = mdContent.split("\n");

  const brief = {
    date,
    title: "",
    status: "",
    mode: "",
    themes: [],
    summaryParagraphs: [],
    summaryText: "",
    leadTakeaway: "",
    published: [],   // { rank, title, sourceText, sourceUrl, category, published, facts, takeaway, uncertainty }
    monitored: [],
    allLinks: [],    // { tag, title, url }
    rejectedCount: 0,
  };

  // Parse the top-level title
  const titleLine = lines.find((l) => l.startsWith("# "));
  if (titleLine) brief.title = titleLine.replace(/^# /, "").trim();

  // Parse metadata fields (key: value lines near the top)
  for (const line of lines.slice(0, 15)) {
    if (line.startsWith("Date: ")) brief.date = line.replace("Date: ", "").trim();
    if (line.startsWith("Status: ")) brief.status = line.replace("Status: ", "").trim();
    if (line.startsWith("Mode: ")) brief.mode = line.replace("Mode: ", "").trim();
  }

  // Split into sections by "## "
  const sections = {};
  let currentSection = "_preamble";
  let sectionLines = [];

  for (const line of lines) {
    if (line.startsWith("## ")) {
      sections[currentSection] = sectionLines.join("\n");
      currentSection = line.replace(/^## /, "").trim().toLowerCase();
      sectionLines = [];
    } else {
      sectionLines.push(line);
    }
  }
  sections[currentSection] = sectionLines.join("\n");

  // Parse daily summary section
  const summary = sections["daily summary"] || "";
  const themeLine = summary.split("\n").find((l) => l.startsWith("Themes:"));
  if (themeLine) {
    brief.themes = themeLine
      .replace("Themes:", "")
      .replace(/\.$/, "")
      .split("•")
      .map((t) => t.trim())
      .filter(Boolean);
  }
  // Preserve the whole daily-summary lede for the site. The first paragraph stays
  // as leadTakeaway for concise titles/metadata; summaryText is the full lead-in.
  brief.summaryParagraphs = summary
    .split(/\n\s*\n/)
    .map((block) => block.split("\n").map((line) => line.trim()).filter(Boolean).join(" "))
    .filter((paragraph) => paragraph && !paragraph.startsWith("Themes:"));
  brief.summaryText = brief.summaryParagraphs.join(" ");
  if (brief.summaryParagraphs[0]) brief.leadTakeaway = brief.summaryParagraphs[0];

  // Parser helper for item blocks (used by both "worth mentioning" and "monitor")
  function parseItems(sectionText) {
    const items = [];
    // Split by "### N. " item headers
    const itemBlocks = sectionText.split(/\n(?=### \d+\.)/).filter((b) => b.trim());

    for (const block of itemBlocks) {
      const itemLines = block.split("\n");
      const headerLine = itemLines.find((l) => l.startsWith("### "));
      if (!headerLine) continue;

      const rankMatch = headerLine.match(/^### (\d+)\.\s+(.+)$/);
      const item = {
        rank: rankMatch ? parseInt(rankMatch[1], 10) : 0,
        title: rankMatch ? rankMatch[2].trim() : headerLine.replace(/^### /, "").trim(),
        sourceText: "",
        sourceUrl: "",
        category: "",
        published: "",
        facts: [],
        takeaway: "",
        uncertainty: "",
      };

      let inFacts = false;
      for (const line of itemLines.slice(1)) {
        const trimmed = line.trim();

        if (trimmed.startsWith("- Source:")) {
          // "- Source: [name](url)" or "- Source: name"
          const linkMatch = trimmed.match(/\[([^\]]+)\]\(([^)]+)\)/);
          if (linkMatch) {
            item.sourceText = linkMatch[1];
            item.sourceUrl = linkMatch[2];
          } else {
            item.sourceText = trimmed.replace("- Source:", "").trim();
          }
          inFacts = false;
        } else if (trimmed.startsWith("- Category:")) {
          item.category = trimmed.replace("- Category:", "").trim();
          inFacts = false;
        } else if (trimmed.startsWith("- Published:")) {
          item.published = trimmed.replace("- Published:", "").trim().slice(0, 10);
          inFacts = false;
        } else if (trimmed === "Source facts:") {
          inFacts = true;
        } else if (inFacts && trimmed.startsWith("- ")) {
          item.facts.push(trimmed.replace(/^- /, ""));
        } else if (trimmed.startsWith("Builder/operator takeaway:")) {
          item.takeaway = trimmed.replace("Builder/operator takeaway:", "").trim();
          inFacts = false;
        } else if (trimmed.startsWith("Uncertainty:")) {
          item.uncertainty = trimmed.replace("Uncertainty:", "").trim();
          inFacts = false;
        } else if (trimmed && !trimmed.startsWith("- Labels:") && !trimmed.startsWith("- Product relevance:")) {
          // Continuation of takeaway (multi-line)
          if (item.takeaway && !inFacts) {
            item.takeaway += " " + trimmed;
          }
        }
      }

      items.push(item);
    }
    return items;
  }

  // Parse "worth mentioning" section
  const worthSection = sections["worth mentioning"] || "";
  brief.published = parseItems(worthSection);

  // Parse "monitor" section
  const monitorSection = sections["monitor (keep an eye on it)"] || sections["monitor"] || "";
  brief.monitored = parseItems(monitorSection);

  // Parse "all researched links" section
  const linksSection = sections["all researched links (complete index)"] || sections["all researched links"] || "";
  for (const line of linksSection.split("\n")) {
    const linkMatch = line.match(/^- \[([PMR])\] \[([^\]]+)\]\(([^)]+)\)/);
    if (linkMatch) {
      brief.allLinks.push({ tag: linkMatch[1], title: linkMatch[2], url: linkMatch[3] });
    }
  }

  // Parse rejected count
  const rejectedSection = sections["rejected items (not recommended)"] || sections["rejected items"] || "";
  const rejectedMatch = rejectedSection.match(/Rejected:\s*(\d+)/);
  if (rejectedMatch) brief.rejectedCount = parseInt(rejectedMatch[1], 10);

  return brief;
}

// ─── CSS ──────────────────────────────────────────────────────────────────────

const SHARED_CSS = `
  *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }

  :root {
    --bg:        #f9f6f0;
    --bg2:       #f1ece4;
    --bg3:       #e8e0d4;
    --border:    rgba(0,0,0,0.11);
    --text:      #1a1a18;
    --text-dim:  #6a6860;
    --accent:    #1e7a42;
    --accent2:   #155e30;
    --link:      #1e7a42;
    --tag-p:     #e4edd8;
    --tag-m:     #ede8f4;
    --tag-r:     #e8e4dc;
  }

  html { font-size: 17px; }

  body {
    background: var(--bg);
    color: var(--text);
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", system-ui, sans-serif;
    line-height: 1.6;
    min-height: 100vh;
  }

  a { color: var(--link); text-decoration: none; }
  a:hover { text-decoration: underline; color: var(--accent2); }

  /* ── Header ── */
  .site-header {
    border-top: 3px solid var(--accent);
    padding: 1.25rem 1.5rem 0;
    background: var(--bg);
  }

  .header-top {
    display: flex;
    align-items: flex-end;
    justify-content: space-between;
    gap: 1rem;
    flex-wrap: wrap;
  }

  .brand {
    font-family: "Georgia", "Times New Roman", serif;
    font-size: 1.5rem;
    font-weight: normal;
    color: var(--text);
    text-decoration: none;
    line-height: 1;
  }
  .brand:hover { text-decoration: none; color: var(--accent); }

  .brand-tagline {
    font-size: 0.68rem;
    letter-spacing: 0.14em;
    text-transform: uppercase;
    color: var(--text-dim);
    margin-top: 0.35rem;
  }

  .site-nav {
    display: flex;
    gap: 1.25rem;
    font-size: 0.8rem;
    align-items: flex-end;
    padding-bottom: 0.15rem;
  }
  .site-nav a { color: var(--text-dim); text-decoration: none; }
  .site-nav a:hover { color: var(--text); text-decoration: none; }
  .site-nav a.nav-active {
    color: var(--text);
    font-weight: 600;
    border-bottom: 1.5px solid var(--text);
    padding-bottom: 1px;
  }

  .dateline {
    display: flex;
    justify-content: space-between;
    align-items: center;
    margin-top: 0.6rem;
    padding: 0.5rem 0;
    border-top: 0.5px solid var(--border);
    font-size: 0.72rem;
    color: var(--text-dim);
  }

  /* ── Layout ── */
  .page-wrap { max-width: 860px; margin: 0 auto; padding: 1.5rem 1.5rem 4rem; }

  .two-col {
    display: grid;
    grid-template-columns: 1fr 210px;
    gap: 2.5rem;
    align-items: start;
  }

  .sidebar {
    border-left: 0.5px solid var(--border);
    padding-left: 1.75rem;
  }

  .sidebar-block { margin-bottom: 1.5rem; }
  .sidebar-block + .sidebar-block {
    padding-top: 1.5rem;
    border-top: 0.5px solid var(--border);
  }

  /* Single-column pages still get reasonable width */
  main { max-width: 700px; margin: 0 auto; padding: 1.75rem 1.5rem 4rem; }

  /* ── Section labels ── */
  .section-label {
    font-size: 0.65rem;
    font-weight: 700;
    letter-spacing: 0.16em;
    text-transform: uppercase;
    color: var(--accent);
    display: flex;
    align-items: center;
    gap: 0.6rem;
    margin-bottom: 0.85rem;
  }
  .section-label::after {
    content: '';
    flex: 1;
    height: 0.5px;
    background: var(--border);
  }

  /* ── Typography ── */
  h1 {
    font-family: "Georgia", "Times New Roman", serif;
    font-size: 1.5rem;
    font-weight: normal;
    line-height: 1.25;
    color: var(--text);
  }
  h2 {
    font-size: 0.65rem;
    font-weight: 700;
    letter-spacing: 0.16em;
    text-transform: uppercase;
    color: var(--accent);
    display: flex;
    align-items: center;
    gap: 0.6rem;
    margin-top: 1.75rem;
    margin-bottom: 0.85rem;
  }
  h2::after {
    content: '';
    flex: 1;
    height: 0.5px;
    background: var(--border);
  }
  h3 {
    font-family: "Georgia", "Times New Roman", serif;
    font-size: 1rem;
    font-weight: normal;
    color: var(--text);
  }

  p { margin-top: 0.6rem; }

  .meta { font-size: 0.72rem; color: var(--text-dim); margin-top: 0.25rem; }
  .meta span + span::before { content: " · "; }

  /* ── Tags ── */
  .tag {
    display: inline-block;
    font-size: 0.62rem;
    font-weight: 600;
    letter-spacing: 0.08em;
    text-transform: uppercase;
    padding: 0.12em 0.45em;
    border: 0.5px solid var(--border);
    color: var(--text-dim);
    vertical-align: middle;
  }
  .tag-p { background: var(--tag-p); color: #3a6030; }
  .tag-m { background: var(--tag-m); color: #6a5a18; }
  .tag-r { background: var(--tag-r); color: var(--text-dim); }

  /* ── Items ── */
  .item {
    padding: 0.8rem 0;
    border-bottom: 0.5px solid var(--border);
  }
  .item:last-child { border-bottom: none; }

  .item-row { display: flex; gap: 0.65rem; }
  .item-num { font-size: 0.7rem; color: var(--text-dim); min-width: 1rem; padding-top: 0.15rem; flex-shrink: 0; }

  .item-title {
    font-family: "Georgia", "Times New Roman", serif;
    font-size: 0.975rem;
    font-weight: normal;
    color: var(--text);
    line-height: 1.35;
  }
  .item-title a { color: inherit; }
  .item-title a:hover { color: var(--accent); text-decoration: none; }

  .item-takeaway {
    margin-top: 0.3rem;
    font-size: 0.855rem;
    line-height: 1.55;
    color: var(--text-dim);
  }

  .item-facts {
    margin-top: 0.4rem;
    font-size: 0.8rem;
    color: var(--text-dim);
    border-left: 2px solid var(--border);
    padding-left: 0.65rem;
    line-height: 1.5;
  }

  .item-uncertainty {
    margin-top: 0.3rem;
    font-size: 0.78rem;
    color: var(--accent2);
    font-style: italic;
  }

  .item-meta {
    margin-top: 0.3rem;
    font-size: 0.7rem;
    color: var(--text-dim);
    display: flex;
    gap: 0.5rem;
    flex-wrap: wrap;
    align-items: center;
  }

  /* ── Archive rows ── */
  .arc-row {
    display: flex;
    gap: 0.75rem;
    padding: 0.7rem 0;
    border-bottom: 0.5px solid var(--border);
  }
  .arc-row:last-child { border-bottom: none; }
  .arc-date { font-size: 0.75rem; color: var(--text-dim); min-width: 52px; padding-top: 0.1rem; flex-shrink: 0; }
  .arc-text { font-size: 0.855rem; color: var(--text-dim); line-height: 1.45; }
  .arc-meta { font-size: 0.7rem; color: var(--text-dim); margin-top: 0.2rem; opacity: 0.75; }

  /* ── Archive theme pills ── */
  .arc-themes {
    display: flex;
    flex-wrap: wrap;
    gap: 0.3rem;
    margin-top: 0.3rem;
    margin-bottom: 0.15rem;
  }
  .arc-tag {
    display: inline-block;
    font-size: 0.6rem;
    font-weight: 700;
    letter-spacing: 0.07em;
    text-transform: uppercase;
    padding: 0.15em 0.5em;
    border-radius: 2px;
    background: var(--bg2);
    border: 0.5px solid var(--border);
    color: var(--text-dim);
  }

  /* ── Brief value prop ── */
  .brief-valueprop {
    font-size: 0.8rem;
    color: var(--text-dim);
    line-height: 1.55;
    margin-bottom: 0.65rem;
    font-style: italic;
  }

  /* ── Sidebar rows ── */
  .sb-row {
    display: flex;
    justify-content: space-between;
    align-items: baseline;
    padding: 0.4rem 0;
    border-bottom: 0.5px solid var(--border);
    font-size: 0.8rem;
  }
  .sb-row:last-child { border-bottom: none; }
  .sb-row a { color: var(--text-dim); }
  .sb-row a:hover { color: var(--text); text-decoration: none; }
  .sb-count { font-size: 0.7rem; color: var(--text-dim); }

  /* ── Details ── */
  details { margin-top: 0.85rem; }
  details summary {
    cursor: pointer;
    font-size: 0.78rem;
    color: var(--text-dim);
    user-select: none;
    padding: 0.35rem 0;
  }
  details summary:hover { color: var(--text); }
  details[open] summary { color: var(--text); }

  /* ── Link index ── */
  .link-index { margin-top: 0.65rem; font-size: 0.78rem; line-height: 1.75; }
  .link-index a { color: var(--text-dim); }
  .link-index a:hover { color: var(--link); }
  .link-index .li-p a { color: var(--text); }

  /* ── Back link ── */
  .back-link {
    display: inline-block;
    font-size: 0.78rem;
    color: var(--text-dim);
    margin-bottom: 1.5rem;
    text-decoration: none;
  }
  .back-link:hover { color: var(--text); text-decoration: none; }
  .back-link::before { content: "← "; }

  /* ── Summary card (reports) ── */
  .summary-card {
    margin-top: 1rem;
    padding: 0.9rem 1rem;
    background: var(--bg2);
    border: 0.5px solid var(--border);
    border-left: 3px solid var(--accent);
  }
  .summary-card p {
    margin-top: 0.3rem;
    font-size: 0.88rem;
    line-height: 1.6;
    color: var(--text-dim);
  }

  .eyebrow {
    font-size: 0.65rem;
    text-transform: uppercase;
    letter-spacing: 0.14em;
    color: var(--accent);
    font-weight: 700;
  }

  /* ── Raw report ── */
  .raw-report {
    margin-top: 0.9rem;
    white-space: pre-wrap;
    font-family: ui-monospace, SFMono-Regular, Menlo, monospace;
    font-size: 0.74rem;
    line-height: 1.6;
    color: var(--text-dim);
    background: var(--bg2);
    border: 0.5px solid var(--border);
    padding: 0.85rem;
  }

  .item-stack { display: grid; gap: 0; }
  .compact-list { margin-top: 0.65rem; display: grid; gap: 0; }
  .compact-list .item { padding: 0.7rem 0; }

  /* ── Lead takeaway ── */
  .lead-summary {
    font-family: "Georgia", "Times New Roman", serif;
    font-size: 0.975rem;
    font-style: italic;
    color: var(--text-dim);
    line-height: 1.6;
    margin-bottom: 0.85rem;
  }

  /* ── Hero tagline (kept for compatibility) ── */
  .hero-tagline {
    font-family: "Georgia", "Times New Roman", serif;
    font-size: 1.3rem;
    line-height: 1.35;
    color: var(--text);
    font-weight: normal;
    margin-top: 1.5rem;
  }
  .hero-sub {
    font-size: 0.88rem;
    color: var(--text-dim);
    margin-top: 0.45rem;
    line-height: 1.6;
    max-width: 540px;
  }

  /* ── Footer ── */
  footer {
    border-top: 2px solid var(--text);
    padding: 0.85rem 1.5rem;
    display: flex;
    justify-content: space-between;
    align-items: center;
    flex-wrap: wrap;
    gap: 0.5rem;
  }
  .footer-brand {
    font-family: "Georgia", "Times New Roman", serif;
    font-size: 0.9rem;
    color: var(--text);
  }
  .footer-sub { font-size: 0.72rem; color: var(--text-dim); }

  /* ── Subscribe block ── */
  .subscribe-desc {
    font-size: 0.78rem;
    color: var(--text-dim);
    line-height: 1.5;
    margin-bottom: 0.65rem;
    margin-top: 0;
  }

  .subscribe-form {
    display: flex;
    gap: 0.4rem;
    flex-wrap: wrap;
  }

  .subscribe-input {
    flex: 1;
    min-width: 0;
    padding: 0.4em 0.6em;
    font-size: 0.78rem;
    font-family: inherit;
    background: var(--bg);
    color: var(--text);
    border: 1px solid var(--border);
    outline: none;
    border-radius: 0;
    -webkit-appearance: none;
  }
  .subscribe-input:focus { border-color: var(--accent); }
  .subscribe-input::placeholder { color: var(--text-dim); opacity: 0.7; }

  .subscribe-btn {
    padding: 0.4em 0.85em;
    font-size: 0.78rem;
    font-family: inherit;
    font-weight: 600;
    background: var(--accent);
    color: #fff;
    border: none;
    cursor: pointer;
    white-space: nowrap;
    border-radius: 0;
    letter-spacing: 0.02em;
  }
  .subscribe-btn:hover { background: var(--accent2); }

  .subscribe-note {
    margin-top: 0.45rem;
    font-size: 0.65rem;
    color: var(--text-dim);
    opacity: 0.7;
  }

  .subscribe-strip {
    margin-top: 2.5rem;
    padding: 1.1rem 1.25rem;
    background: var(--bg2);
    border: 0.5px solid var(--border);
    border-left: 3px solid var(--accent);
  }
  .subscribe-strip .subscribe-headline {
    font-family: "Georgia", "Times New Roman", serif;
    font-size: 0.95rem;
    font-weight: normal;
    color: var(--text);
    margin-bottom: 0.35rem;
  }

  /* ── Theme toggle button ── */
  .theme-btn {
    background: none;
    border: none;
    cursor: pointer;
    font-size: 1rem;
    color: var(--text-dim);
    padding: 0;
    line-height: 1;
    display: flex;
    align-items: center;
  }
  .theme-btn:hover { color: var(--text); }
  /* ── Inline subscribe strip ── */
  .inline-subscribe {
    margin-bottom: 1.5rem;
    padding-bottom: 1.25rem;
    border-bottom: 0.5px solid var(--border);
  }
  .inline-subscribe .subscribe-form { flex-wrap: nowrap; }


  /* ── Dark mode ── */
  /* Fires when OS is dark AND user hasn't forced light */
  @media (prefers-color-scheme: dark) {
    :root:not([data-theme="light"]) {
      --bg:        #1d1e20;
      --bg2:       #252628;
      --bg3:       #2e2f31;
      --border:    rgba(255,255,255,0.1);
      --text:      #e8e4dc;
      --text-dim:  #9a9488;
      --accent:    #40d070;
      --accent2:   #58e085;
      --link:      #40d070;
      --tag-p:     #192c1e;
      --tag-m:     #241e30;
      --tag-r:     #252628;
    }
  }
  /* Fires when user explicitly chose dark (regardless of OS) */
  :root[data-theme="dark"] {
    --bg:        #1d1e20;
    --bg2:       #252628;
    --bg3:       #2e2f31;
    --border:    rgba(255,255,255,0.1);
    --text:      #e8e4dc;
    --text-dim:  #9a9488;
    --accent:    #40d070;
    --accent2:   #58e085;
    --link:      #40d070;
    --tag-p:     #192c1e;
    --tag-m:     #241e30;
    --tag-r:     #252628;
  }
`;

const CSS_LINK = '<link rel="stylesheet" href="/style.css">';

// Runs before CSS paints — sets data-theme from localStorage to prevent FOUC
const THEME_INIT = `<script>(function(){var t=localStorage.getItem('nl-theme');if(t)document.documentElement.setAttribute('data-theme',t);})()</script>`;

// Toggle function + icon sync — injected before </body> on every page
const THEME_JS = `<script>
function _nlThemeToggle(){
  var h=document.documentElement;
  var cur=h.getAttribute('data-theme');
  var isDark=cur==='dark'||(cur!=='light'&&window.matchMedia('(prefers-color-scheme:dark)').matches);
  var next=isDark?'light':'dark';
  h.setAttribute('data-theme',next);
  localStorage.setItem('nl-theme',next);
  var btn=document.getElementById('nl-theme-btn');
  if(btn)btn.textContent=next==='dark'?'☀':'☾';
}
(function(){
  var h=document.documentElement;
  var cur=h.getAttribute('data-theme');
  var isDark=cur==='dark'||(cur!=='light'&&window.matchMedia('(prefers-color-scheme:dark)').matches);
  var btn=document.getElementById('nl-theme-btn');
  if(btn)btn.textContent=isDark?'☀':'☾';
})();
</script>`;

function siteNav(active = "") {
  const items = [
    { href: "/", label: "Archive", key: "archive" },
    { href: "/reports/", label: "Reports", key: "reports" },
  ];

  const links = items.map((item) => {
    const cls = item.key === active ? ` class="nav-active"` : "";
    return `<a href="${item.href}"${cls}>${item.label}</a>`;
  }).join("");

  return links + `<button id="nl-theme-btn" class="theme-btn" onclick="_nlThemeToggle()" aria-label="Toggle dark mode">&#9790;</button>`;
}

function renderRawMarkdown(markdown) {
  return `<details>
      <summary>Original markdown</summary>
      <pre class="raw-report">${esc(markdown)}</pre>
    </details>`;
}

function briefSummaryText(brief) {
  if (brief.summaryText) return brief.summaryText;
  if (Array.isArray(brief.summaryParagraphs) && brief.summaryParagraphs.length) {
    return brief.summaryParagraphs.join(" ");
  }
  return brief.leadTakeaway || "";
}

// ─── Brief page renderer ──────────────────────────────────────────────────────

function renderBriefPage(brief) {
  const dateLabel = formatDate(brief.date);
  const published = brief.published;
  const monitored = brief.monitored;
  const summaryText = briefSummaryText(brief);

  function renderItem(item) {
    const sourceLink = item.sourceUrl
      ? `<a href="${esc(item.sourceUrl)}" target="_blank" rel="noopener">${esc(item.sourceText || item.sourceUrl)}</a>`
      : esc(item.sourceText || "");

    const titleEl = item.sourceUrl
      ? `<a href="${esc(item.sourceUrl)}" target="_blank" rel="noopener">${esc(item.title)}</a>`
      : esc(item.title);

    const factsHtml = item.facts.length
      ? `<div class="item-facts">${item.facts.map((f) => `<div>${renderText(f)}</div>`).join("")}</div>`
      : "";

    const uncertaintyHtml = item.uncertainty
      ? `<div class="item-uncertainty">⚠ Uncertainty: ${renderText(item.uncertainty)}</div>`
      : "";

    return `
    <div class="item">
      <div class="item-row">
        <span class="item-num">${item.rank}.</span>
        <div>
          <div class="item-title">${titleEl}</div>
          ${item.takeaway ? `<div class="item-takeaway">${renderText(item.takeaway)}</div>` : ""}
          ${factsHtml}
          ${uncertaintyHtml}
          <div class="item-meta">
            ${sourceLink ? `<span>${sourceLink}</span>` : ""}
            ${item.category ? `<span>${esc(item.category)}</span>` : ""}
            ${item.published ? `<span>${esc(item.published)}</span>` : ""}
          </div>
        </div>
      </div>
    </div>`;
  }

  const publishedHtml = published.length
    ? `<h2>Worth mentioning</h2>\n${published.map(renderItem).join("\n")}`
    : "";

  const monitoredHtml = monitored.length
    ? `<h2>Monitor</h2>\n${monitored.map(renderItem).join("\n")}`
    : "";

  const linkIndex = brief.allLinks.length
    ? `<details>
      <summary>${brief.allLinks.length} researched links (full index)</summary>
      <div class="link-index">
        ${brief.allLinks.map((l) => {
          const cls = `li-${l.tag.toLowerCase()}`;
          return `<div class="${cls}"><span class="tag tag-${l.tag.toLowerCase()}">${esc(l.tag)}</span> <a href="${esc(l.url)}" target="_blank" rel="noopener">${esc(l.title)}</a></div>`;
        }).join("\n        ")}
      </div>
    </details>`
    : "";

  return `<!DOCTYPE html>
<html lang="en">
<head>
  ${THEME_INIT}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>${esc(dateLabel)} — ${esc(SITE_NAME)}</title>
${seoMeta({ title: dateLabel, description: summaryText || brief.themes.join(", ") || SITE_DESCRIPTION, path: `/briefs/${brief.date}/`, type: "article", publishedDate: brief.date, leadTitle: brief.published[0]?.title || "" })}
  ${CSS_LINK}
</head>
<body>
  <header class="site-header">
    <div class="header-top">
      <div>
        <a class="brand" href="/">The Nightly Librarian</a>
        <p class="brand-tagline">AI signal without the noise</p>
      </div>
      <nav class="site-nav">${siteNav("archive")}</nav>
    </div>
    <div class="dateline">
      <span>${esc(dateLabel)}</span>
      <span style="font-style:italic;">What changed. Why it matters. What to do.</span>
    </div>
  </header>
  <main>
    <a class="back-link" href="/">All briefs</a>
    <h1>${esc(dateLabel)}</h1>
    ${brief.themes.length ? `<div class="meta" style="margin-top:0.4rem;">${brief.themes.map((t) => `<span>${esc(t)}</span>`).join("")}</div>` : ""}
    ${brief.published[0]?.takeaway ? `<p class="lead-summary" style="margin-top:0.85rem;">${renderText(brief.published[0].takeaway)}</p>` : brief.themes.length ? `<p class="lead-summary" style="margin-top:0.85rem;">${esc(brief.themes.join(" · "))}</p>` : ""}
    ${publishedHtml}
    ${monitoredHtml}
    ${linkIndex}
    ${subscribeStrip()}
  </main>
  <footer>
    <span class="footer-brand">The Nightly Librarian</span>
    <span class="footer-sub">Built for builders, not boardrooms.</span>
  </footer>
  ${THEME_JS}
</body>
</html>
`;
}

// ─── Report renderers ──────────────────────────────────────────────────────────

function renderDailyReportPage(report) {
  const worthAttentionHtml = report.worthAttention.length
    ? `<h2>Worth attention</h2>
    <div class="item-stack">
      ${report.worthAttention.map((item) => `
      <div class="item">
        <div class="item-title">${item.url ? `<a href="${esc(item.url)}" target="_blank" rel="noopener">${esc(item.title)}</a>` : esc(item.title)}</div>
        ${item.summary ? `<div class="item-takeaway">${renderText(item.summary)}</div>` : ""}
      </div>`).join("\n")}
    </div>`
    : "";

  const digestHtml = report.fullDigest.length
    ? `<h2>Full digest</h2>
    <div class="compact-list">
      ${report.fullDigest.map((item) => `
      <div class="item">
        <div class="item-title">
          <span class="tag tag-${esc(item.tag.toLowerCase())}">${esc(item.tag)}</span>
          ${item.url ? `<a href="${esc(item.url)}" target="_blank" rel="noopener">${esc(item.title)}</a>` : esc(item.title)}
        </div>
        ${item.summary ? `<div class="item-takeaway">${renderText(item.summary)}</div>` : ""}
        <div class="item-meta">
          ${item.source ? `<span>${esc(item.source)}</span>` : ""}
        </div>
      </div>`).join("\n")}
    </div>`
    : "";

  return `<!DOCTYPE html>
<html lang="en">
<head>
  ${THEME_INIT}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>${esc(formatDate(report.date))} report log — ${esc(SITE_NAME)}</title>
${seoMeta({ title: `${formatDate(report.date)} report log`, description: report.summary.text, path: `/reports/${report.date}/` })}
  ${CSS_LINK}
</head>
<body>
  <header class="site-header">
    <div class="header-top">
      <div>
        <a class="brand" href="/">The Nightly Librarian</a>
        <p class="brand-tagline">AI signal without the noise</p>
      </div>
      <nav class="site-nav">${siteNav("reports")}</nav>
    </div>
    <div class="dateline">
      <span>${esc(formatDate(report.date))} · Report log</span>
      ${report.completedAt ? `<span>${esc(formatIsoDateTime(report.completedAt))}</span>` : ""}
    </div>
  </header>
  <main>
    <a class="back-link" href="/reports/">All reports</a>
    <h1>${esc(formatDate(report.date))}</h1>
    <div class="summary-card">
      <div class="eyebrow">Report summary</div>
      <p>${esc(report.summary.text)}</p>
      <div class="meta" style="margin-top:0.4rem;">
        ${report.summary.stats.map((item) => `<span>${esc(item)}</span>`).join("")}
      </div>
    </div>
    ${worthAttentionHtml}
    ${digestHtml}
    ${renderRawMarkdown(report.rawMarkdown)}
  </main>
  <footer>
    <span class="footer-brand">The Nightly Librarian</span>
    <span class="footer-sub">Built for builders, not boardrooms.</span>
  </footer>
  ${THEME_JS}
</body>
</html>
`;
}

function renderLegacyReportPage(report) {
  const signalsHtml = report.signals.length
    ? `<h2>Signals</h2>
    <div class="item-stack">
      ${report.signals.map((item, index) => `
      <div class="item">
        <div class="item-title">${index + 1}. ${esc(item.title)}</div>
        ${item.body ? `<div class="item-takeaway">${renderText(item.body)}</div>` : ""}
      </div>`).join("\n")}
    </div>`
    : "";

  const tryThisHtml = report.tryThis
    ? `<h2>Try this</h2><div class="item"><div class="item-takeaway">${renderText(report.tryThis)}</div></div>`
    : "";

  const verdictHtml = report.verdict
    ? `<h2>Librarian's verdict</h2><div class="item"><div class="item-takeaway">${renderText(report.verdict)}</div></div>`
    : "";

  return `<!DOCTYPE html>
<html lang="en">
<head>
  ${THEME_INIT}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>${esc(formatDate(report.date))} legacy archive — ${esc(SITE_NAME)}</title>
${seoMeta({ title: `${formatDate(report.date)} legacy archive`, description: report.summary.text, path: `/reports/legacy/${report.slug}/` })}
  ${CSS_LINK}
</head>
<body>
  <header class="site-header">
    <div class="header-top">
      <div>
        <a class="brand" href="/">The Nightly Librarian</a>
        <p class="brand-tagline">AI signal without the noise</p>
      </div>
      <nav class="site-nav">${siteNav("reports")}</nav>
    </div>
    <div class="dateline">
      <span>${esc(formatDate(report.date))} · Legacy archive</span>
      <span>${esc(report.slug)}</span>
    </div>
  </header>
  <main>
    <a class="back-link" href="/reports/">All reports</a>
    <h1>${esc(formatDate(report.date))}</h1>
    <div class="summary-card">
      <div class="eyebrow">Archive summary</div>
      <p>${esc(report.summary.text)}</p>
      <div class="meta" style="margin-top:0.4rem;">
        ${report.summary.stats.map((item) => `<span>${esc(item)}</span>`).join("")}
      </div>
    </div>
    ${signalsHtml}
    ${tryThisHtml}
    ${verdictHtml}
    ${renderRawMarkdown(report.rawMarkdown)}
  </main>
  <footer>
    <span class="footer-brand">The Nightly Librarian</span>
    <span class="footer-sub">Built for builders, not boardrooms.</span>
  </footer>
  ${THEME_JS}
</body>
</html>
`;
}

function renderReportsIndexPage(reports, legacyReports) {
  const sortedReports = [...reports].sort((a, b) => b.date.localeCompare(a.date));
  const sortedLegacyReports = [...legacyReports].sort((a, b) => b.slug.localeCompare(a.slug));

  const recentRows = sortedReports.map((report) => `
    <div class="item">
      <div class="item-title"><a href="/reports/${esc(report.slug)}/">${esc(formatDate(report.date))}</a></div>
      <div class="item-takeaway">${renderText(report.summary.text)}</div>
      <div class="item-meta">
        ${report.summary.stats.map((item) => `<span>${esc(item)}</span>`).join("")}
      </div>
    </div>`).join("\n");

  const legacyRows = sortedLegacyReports.map((report) => `
    <div class="item">
      <div class="item-title"><a href="/reports/legacy/${esc(report.slug)}/">${esc(formatDate(report.date))}</a></div>
      <div class="item-takeaway">${renderText(report.summary.text)}</div>
      <div class="item-meta">
        <span>${esc(report.issue || "Legacy archive")}</span>
        <span>${esc(report.slug)}</span>
      </div>
    </div>`).join("\n");

  return `<!DOCTYPE html>
<html lang="en">
<head>
  ${THEME_INIT}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Reports — ${esc(SITE_NAME)}</title>
${seoMeta({ title: "Reports", description: "Pipeline report log and legacy archive entries — The Nightly Librarian.", path: "/reports/" })}
  ${CSS_LINK}
</head>
<body>
  <header class="site-header">
    <div class="header-top">
      <div>
        <a class="brand" href="/">The Nightly Librarian</a>
        <p class="brand-tagline">AI signal without the noise</p>
      </div>
      <nav class="site-nav">${siteNav("reports")}</nav>
    </div>
    <div class="dateline">
      <span>Report log</span>
      <span>Pipeline drafts and archive snapshots</span>
    </div>
  </header>
  <main>
    <h1>Report log</h1>
    <p style="margin-top:0.5rem;font-size:0.88rem;color:var(--text-dim);line-height:1.6;max-width:600px;">Nightly report drafts from the Codex morning memo pipeline, plus preserved legacy archive snapshots from the earlier issue format.</p>
    ${reports.length ? `<h2>Recent reports</h2>${recentRows}` : ""}
    ${legacyReports.length ? `<h2>Legacy archive</h2>${legacyRows}` : ""}
  </main>
  <footer>
    <span class="footer-brand">The Nightly Librarian</span>
    <span class="footer-sub">Built for builders, not boardrooms.</span>
  </footer>
  ${THEME_JS}
</body>
</html>
`;
}

// ─── Brief page from report data (fallback for dates missing a dist/briefs entry) ──

function renderBriefFromReport(report) {
  const dateLabel = formatDate(report.date);
  const items = report.worthAttention;

  function renderItem(item) {
    const titleEl = item.url
      ? `<a href="${esc(item.url)}" target="_blank" rel="noopener">${esc(item.title)}</a>`
      : esc(item.title);
    const sourceLink = item.url
      ? `<a href="${esc(item.url)}" target="_blank" rel="noopener">${esc(new URL(item.url).hostname.replace(/^www\./, ""))}</a>`
      : "";
    return `
    <div class="item">
      <div class="item-title">${titleEl}</div>
      ${item.summary ? `<div class="item-takeaway">${renderText(item.summary)}</div>` : ""}
      <div class="item-meta">
        ${sourceLink ? `<span>${sourceLink}</span>` : ""}
        ${item.source ? `<span>${esc(item.source)}</span>` : ""}
      </div>
    </div>`;
  }

  const leadTakeaway = report.summary.text;

  return `<!DOCTYPE html>
<html lang="en">
<head>
  ${THEME_INIT}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>${esc(dateLabel)} — ${esc(SITE_NAME)}</title>
${seoMeta({ title: dateLabel, description: leadTakeaway || SITE_DESCRIPTION, path: `/briefs/${report.date}/`, type: "article", publishedDate: report.date, leadTitle: report.worthAttention[0]?.title || "" })}
  ${CSS_LINK}
</head>
<body>
  <header class="site-header">
    <a class="brand" href="/">The Nightly Librarian</a>
    <span class="brand-tagline">AI signal without the noise</span>
    <nav class="site-nav">${siteNav("archive")}</nav>
  </header>
  <main>
    <a class="back-link" href="/">All briefs</a>
    <h1>${esc(dateLabel)}</h1>
    ${leadTakeaway ? `<p style="margin-top:1.25rem;font-size:1.05rem;line-height:1.65;">${renderText(leadTakeaway)}</p>` : ""}
    ${items.length ? `<h2>Worth mentioning</h2>\n${items.map(renderItem).join("\n")}` : ""}
  </main>
  <footer>
    The Nightly Librarian — built for builders, not boardrooms.
  </footer>
  ${THEME_JS}
</body>
</html>
`;
}

// ─── Index page renderer ──────────────────────────────────────────────────────

function renderIndexPage(briefs, reports, legacyReports) {
  // briefs sorted newest-first
  const sorted = [...briefs].sort((a, b) => b.date.localeCompare(a.date));
  const latest = sorted[0];
  const latestSummary = latest ? briefSummaryText(latest) : "";
  const sortedLegacyReports = [...legacyReports].sort((a, b) => b.slug.localeCompare(a.slug));

  function renderArchiveRow(brief) {
    const lead = brief.published[0];
    return `
    <div class="item">
      <div class="item-title" style="font-family:'Georgia',serif;font-size:0.92rem;">
        <a href="/briefs/${esc(brief.date)}/" style="color:var(--text);">${esc(formatDateShort(brief.date))}</a>
      </div>
      ${brief.themes.length ? `<div class="arc-themes">${brief.themes.slice(0,2).map((t) => `<span class="arc-tag">${esc(t)}</span>`).join("")}</div>` : ""}
      ${lead ? `<div class="item-takeaway" style="font-size:0.88rem;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;">${renderText(lead.takeaway || lead.title)}</div>` : ""}
      <div class="item-meta">
        <span>${brief.published.length} item${brief.published.length !== 1 ? "s" : ""}</span>
        ${brief.monitored.length ? `<span>${brief.monitored.length} to watch</span>` : ""}
        ${brief.allLinks.length ? `<span>${brief.allLinks.length} links researched</span>` : ""}
      </div>
    </div>`;
  }

  // Today's brief items (from latest)
  const latestItemsHtml = latest && latest.published.length
    ? latest.published.slice(0, 5).map((item, i) => `
    <div class="item">
      <div class="item-row">
        <span class="item-num">${i + 1}.</span>
        <div>
          <div class="item-title">${item.sourceUrl ? `<a href="${esc(item.sourceUrl)}" target="_blank" rel="noopener">${esc(item.title)}</a>` : esc(item.title)}</div>
          ${item.takeaway ? `<div class="item-takeaway">${renderText(item.takeaway)}</div>` : ""}
          <div class="item-meta">
            ${item.sourceText ? `<span>${item.sourceUrl ? `<a href="${esc(item.sourceUrl)}" target="_blank" rel="noopener">${esc(item.sourceText)}</a>` : esc(item.sourceText)}</span>` : ""}
            ${item.category ? `<span>${esc(item.category)}</span>` : ""}
          </div>
        </div>
      </div>
    </div>`).join("\n")
    : latest
      ? `<div class="item"><div class="item-takeaway">${renderText(latestSummary)}</div></div>`
      : "";

  // Archive rows (skip latest, already shown)
  const archiveRows = sorted.slice(1).map(renderArchiveRow).join("\n");

  // Sidebar report log
  const sortedReports = [...reports].sort((a, b) => b.date.localeCompare(a.date));
  const reportLogRows = sortedReports.slice(0, 6).map((r) => `
    <div class="sb-row">
      <a href="/reports/${esc(r.slug)}/">${esc(formatDateShort(r.date))}</a>
      <span class="sb-count">${r.worthAttention.length} item${r.worthAttention.length !== 1 ? "s" : ""}</span>
    </div>`).join("\n");

  return `<!DOCTYPE html>
<html lang="en">
<head>
  ${THEME_INIT}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>${esc(SITE_NAME)} — AI signal without the noise</title>
${seoMeta({ title: SITE_NAME, description: SITE_DESCRIPTION, path: "/" })}
  ${CSS_LINK}
</head>
<body>
  <header class="site-header">
    <div class="header-top">
      <div>
        <a class="brand" href="/">The Nightly Librarian</a>
        <p class="brand-tagline">AI signal without the noise</p>
      </div>
      <nav class="site-nav">${siteNav("archive")}</nav>
    </div>
    ${latest ? `<div class="dateline">
      <span>Latest issue · ${esc(formatDate(latest.date))}</span>
      <span style="font-style:italic;">What changed. Why it matters. What to do.</span>
    </div>` : ""}
  </header>

  <div class="page-wrap">
    <div class="two-col">
      <div>
        ${latest ? `
        <div class="inline-subscribe">
          <form class="subscribe-form" action="https://thenightlylibrarian.substack.com/subscribe" method="GET" target="_blank">
            <input class="subscribe-input" type="email" name="email" placeholder="your@email.com" required>
            <button class="subscribe-btn" type="submit">Get the brief free →</button>
          </form>
        </div>
        <div class="section-label">Today's brief</div>
        <p class="brief-valueprop">Every morning I read a few hundred links so you don't have to. This is what cleared the bar today.</p>
        ${latest.themes.length ? `<div class="meta" style="margin-bottom:0.5rem;">${latest.themes.map((t) => `<span>${esc(t)}</span>`).join("")}</div>` : ""}
        ${latest && latest.published[0]?.takeaway ? `<p class="lead-summary">${renderText(latest.published[0].takeaway)}</p>` : latest && latest.themes.length ? `<p class="lead-summary">${esc(latest.themes.join(" · "))}</p>` : ""}
        <div style="border-top:0.5px solid var(--border);">
          ${latestItemsHtml}
        </div>
        <a href="/briefs/${esc(latest.date)}/" style="display:inline-block;margin-top:0.85rem;font-size:0.82rem;color:var(--accent);font-weight:600;border-bottom:1px solid var(--accent);padding-bottom:1px;">Read the full brief →</a>
        ` : ""}

        ${sorted.length > 1 ? `
        <div style="margin-top:1.75rem;">
          <div class="section-label">Archive</div>
          ${archiveRows}
        </div>` : ""}
      </div>

      <aside class="sidebar">
        ${subscribeSidebar()}
        <div class="sidebar-block">
          <div class="section-label">About</div>
          <p style="font-size:0.82rem;line-height:1.6;color:var(--text-dim);">I scan AI papers, GitHub PRs, model releases, and dev tooling every night and distill what actually changes how you build. If it wouldn't make you stop and reconsider something, it doesn't make the brief.</p>
        </div>

        ${reportLogRows ? `
        <div class="sidebar-block">
          <div class="section-label">Report log</div>
          ${reportLogRows}
          <a href="/reports/" style="display:inline-block;margin-top:0.6rem;font-size:0.72rem;color:var(--text-dim);">All reports →</a>
        </div>` : ""}
      </aside>
    </div>
  </div>

  <footer>
    <span class="footer-brand">The Nightly Librarian</span>
    <span class="footer-sub">Built for builders, not boardrooms.</span>
  </footer>
  ${THEME_JS}
</body>
</html>
`;
}

// ─── RSS feed builder ──────────────────────────────────────────────────────────

function buildRssFeed(briefs) {
  // newest-first, cap at 20 items
  const sorted = [...briefs].sort((a, b) => b.date.localeCompare(a.date)).slice(0, 20);

  const items = sorted.map((brief) => {
    const url = `${SITE_URL}/briefs/${brief.date}/`;
    const summaryText = briefSummaryText(brief);
    const title = `${formatDate(brief.date)}${brief.leadTakeaway ? ` — ${brief.leadTakeaway.slice(0, 100)}` : ""}`;
    const themes = brief.themes.length ? `<p>Topics: ${brief.themes.join(" · ")}</p>` : "";
    const topItems = brief.published.slice(0, 3).map((item) =>
      `<li>${item.title}${item.takeaway ? `: ${item.takeaway}` : ""}</li>`
    ).join("");
    const descBody = [
      summaryText ? `<p>${summaryText}</p>` : "",
      themes,
      topItems ? `<ul>${topItems}</ul>` : "",
      `<p><a href="${url}">Read the full brief →</a></p>`,
    ].filter(Boolean).join("\n");

    // RFC-2822 pubDate — treat brief date as 6 AM UTC
    const pubDate = new Date(`${brief.date}T06:00:00Z`).toUTCString();

    return `    <item>
      <title>${esc(title)}</title>
      <link>${url}</link>
      <guid isPermaLink="true">${url}</guid>
      <pubDate>${pubDate}</pubDate>
      <description><![CDATA[${descBody}]]></description>
    </item>`;
  }).join("\n");

  return `<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:content="http://purl.org/rss/1.0/modules/content/">
  <channel>
    <title>${SITE_NAME}</title>
    <link>${SITE_URL}</link>
    <description>${SITE_DESCRIPTION}</description>
    <language>en-us</language>
    <atom:link href="${SITE_URL}/feed.xml" rel="self" type="application/rss+xml"/>
    <lastBuildDate>${new Date().toUTCString()}</lastBuildDate>
    <ttl>360</ttl>
${items}
  </channel>
</rss>`;
}

// ─── Sitemap builder ──────────────────────────────────────────────────────────

function buildSitemap(briefs, reports, legacyReports) {
  const now = new Date().toISOString().slice(0, 10);

  const urls = [
    { loc: `${SITE_URL}/`, priority: "1.0", changefreq: "daily" },
    { loc: `${SITE_URL}/reports/`, priority: "0.5", changefreq: "daily" },
    ...briefs
      .sort((a, b) => b.date.localeCompare(a.date))
      .map((b) => ({ loc: `${SITE_URL}/briefs/${b.date}/`, priority: "0.8", changefreq: "never", lastmod: b.date })),
    ...reports
      .sort((a, b) => b.date.localeCompare(a.date))
      .map((r) => ({ loc: `${SITE_URL}/reports/${r.date}/`, priority: "0.4", changefreq: "never", lastmod: r.date })),
  ];

  const urlEntries = urls.map(({ loc, priority, changefreq, lastmod }) => `  <url>
    <loc>${loc}</loc>
    <lastmod>${lastmod || now}</lastmod>
    <changefreq>${changefreq}</changefreq>
    <priority>${priority}</priority>
  </url>`).join("\n");

  return `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urlEntries}
</urlset>`;
}

// ─── Main ─────────────────────────────────────────────────────────────────────

function main() {
  if (!fs.existsSync(BRIEFS_MD_DIR)) {
    console.error(`dist/briefs/ not found at ${BRIEFS_MD_DIR}`);
    process.exit(1);
  }

  const mdFiles = fs.readdirSync(BRIEFS_MD_DIR)
    .filter((f) => /^\d{4}-\d{2}-\d{2}\.md$/.test(f))
    .sort();

  if (!mdFiles.length) {
    console.error("No brief markdown files found in dist/briefs/");
    process.exit(1);
  }

  const briefs = [];
  const reports = [];
  const legacyReports = [];

  for (const filename of mdFiles) {
    const date = filename.replace(".md", "");
    const mdPath = path.join(BRIEFS_MD_DIR, filename);
    const content = fs.readFileSync(mdPath, "utf8");
    const brief = parseBriefMd(content, date);
    if (!brief) continue;

    briefs.push(brief);

    // Write individual brief page
    const briefPagePath = path.join(SITE_BRIEFS_DIR, date, "index.html");
    write(briefPagePath, renderBriefPage(brief));
  }

  if (fs.existsSync(REPORTS_MD_DIR)) {
    const reportFiles = fs.readdirSync(REPORTS_MD_DIR)
      .filter((file) => /^\d{4}-\d{2}-\d{2}\.md$/.test(file))
      .sort()
      .reverse();

    for (const filename of reportFiles) {
      const date = filename.replace(".md", "");
      const filePath = path.join(REPORTS_MD_DIR, filename);
      const report = parseDailyReportMarkdown(fs.readFileSync(filePath, "utf8"), date);
      reports.push(report);
      write(path.join(SITE_REPORTS_DIR, date, "index.html"), renderDailyReportPage(report));
    }
  }

  for (const filePath of listLegacyBriefFiles()) {
    const slug = path.basename(path.dirname(filePath));
    const legacy = parseLegacyReportMarkdown(fs.readFileSync(filePath, "utf8"), slug);
    if (!legacy) continue;
    legacyReports.push(legacy);
    write(path.join(SITE_REPORTS_DIR, "legacy", slug, "index.html"), renderLegacyReportPage(legacy));
  }

  // Generate brief pages from report data for any date missing a dist/briefs entry
  const briefDates = new Set(briefs.map((b) => b.date));
  for (const report of reports) {
    if (!briefDates.has(report.date) && report.worthAttention.length > 0) {
      const briefPagePath = path.join(SITE_BRIEFS_DIR, report.date, "index.html");
      write(briefPagePath, renderBriefFromReport(report));
      // Add a lightweight stub to briefs array so it appears in the archive index
      briefs.push({
        date: report.date,
        title: report.title,
        themes: [],
        summaryParagraphs: [report.summary.text],
        summaryText: report.summary.text,
        leadTakeaway: report.summary.text,
        published: report.worthAttention.map((item) => ({
          title: item.title,
          takeaway: item.summary || "",
          sourceUrl: item.url || "",
          sourceText: item.source || "",
          category: "",
          published: "",
          facts: [],
          uncertainty: "",
        })),
        monitored: [],
        allLinks: [],
      });
      briefDates.add(report.date);
    }
  }

  // Write shared stylesheet
  write(path.join(SITE_DIR, "style.css"), SHARED_CSS.trim());

  // Write index page
  write(path.join(SITE_DIR, "index.html"), renderIndexPage(briefs, reports, legacyReports));
  write(path.join(SITE_REPORTS_DIR, "index.html"), renderReportsIndexPage(reports, legacyReports));

  // Write RSS feed
  const allBriefs = [...briefs].sort((a, b) => b.date.localeCompare(a.date));
  write(path.join(SITE_DIR, "feed.xml"), buildRssFeed(allBriefs));

  // Write sitemap
  write(path.join(SITE_DIR, "sitemap.xml"), buildSitemap(allBriefs, reports, legacyReports));

  console.log(`\nBuild complete. ${briefs.length} brief(s), ${reports.length} report(s), ${legacyReports.length} legacy archive entr${legacyReports.length === 1 ? "y" : "ies"} → site/`);
  if (DRY_RUN) console.log("(dry run — no files written)");
}

if (require.main === module) {
  main();
}

module.exports = {
  buildRssFeed,
  briefSummaryText,
  parseBriefMd,
  renderBriefPage,
  renderIndexPage,
};
